# The MCP sidecar — a TypeScript/Node package, built the same way every future
# non-PHP workload in this family is supposed to be: `buildNpmPackage` away from an
# image with the shared uid, labels, empty `/bin` and checks. See
# docs/adr/0013-nix-built-container-images.md, "New workloads are born into this."
#
# Unlike the label renderer and worker, this workload's source lives in this
# repository (mcp/) rather than a pinned external one — see mcp/README.md and
# docs/mcp-interface-spec.md's Open Question 1 amendment (2026-09-19) for why.
#
# **Unbuilt.** `npmDepsHash` is a placeholder (nix/hashes.nix, `mcpNpmDeps`) because
# `mcp/package-lock.json` does not exist yet — it is generated by `npm install` in an
# environment with npm registry access, which the sandbox that wrote this file did not
# have. The first `nix build .#mcp` after that lockfile is committed will fail on
# purpose with the real hash, exactly as nix/README.md's "Bootstrapping the hashes"
# describes for the other two fixed-output derivations.
{
  lib,
  buildNpmPackage,
  hashes,
  sources,
  version,
}:

buildNpmPackage (finalAttrs: {
  pname = "victual-mcp";
  inherit version;

  src = sources.toSource sources.mcpFiles;

  npmDepsHash = hashes.mcpNpmDeps;

  npmBuildScript = "build";

  # The contract tests (tests/contract, once plan 14's fixtures are copied in) run in CI
  # against a live compose stack per spec §11.1, not as part of this derivation — a
  # fixture mismatch should fail a workflow attributable to the change that caused it,
  # not an unrelated flake.lock bump. Left as the default (npm's own `test` script is not
  # invoked by buildNpmPackage unless doCheck is set) rather than an explicit doCheck =
  # false, since there is no test script wired to a real fixture yet to skip.

  meta = {
    description = "Victual MCP sidecar — read-only tools over Victual's REST API";
    homepage = "https://github.com/datagen24/victual";
    license = lib.licenses.mit;
    mainProgram = "victual-mcp";
    platforms = lib.platforms.all;
  };
})
