-- Disposable spike for ADR-0022 acceptance prerequisites 1, 2, 3, 5, 6 and 7
-- (docs/adr/0022-open-containers-carry-a-measured-remainder.md). Not part of plan 28's
-- migration 0277, which stays unwritten until that plan is scheduled — see
-- migrations/RESERVATIONS.md. This file exists only on the disposable spike branch.
--
-- quantity_units, quantity_unit_conversions, products, stock, stock_log, and the
-- quantity_unit_conversions_resolved view as they stand in db/pgsql/baseline/01_tables.sql
-- and db/pgsql/baseline/03_views_group2.sql today, trimmed to the columns this spike
-- touches. Copied rather than sourced from the real baseline so this spike has no
-- dependency on the other 30+ tables those files declare.

CREATE TABLE quantity_units (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	name_plural TEXT
);

CREATE TABLE quantity_unit_conversions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	from_qu_id INTEGER NOT NULL,
	to_qu_id INTEGER NOT NULL,
	factor DOUBLE PRECISION NOT NULL,
	product_id INTEGER
);

CREATE TABLE products (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	qu_id_stock INTEGER NOT NULL,
	-- Retained for the negative control (acceptance prerequisite 1) only. Plan 28's
	-- decisions 4 and 7 retire this mechanism; this spike does not touch its retirement,
	-- only reproduces the arithmetic ADR-0022's Context quotes to demonstrate it against
	-- real rows rather than the source read alone.
	enable_tare_weight_handling SMALLINT NOT NULL DEFAULT 0,
	tare_weight DOUBLE PRECISION NOT NULL DEFAULT 0
);

-- stock and stock_log as they stand in the baseline today, trimmed to the columns this
-- spike reads or writes. The four measurement columns (opened_amount, opened_qu_id,
-- opened_tare, opened_measured_at) and the coherence constraint are 01-stock-measurement's
-- job, applied after this file and after 02-seed.sql's unmeasured baseline rows exist.
CREATE TABLE stock (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER NOT NULL,
	amount DOUBLE PRECISION NOT NULL,
	best_before_date DATE,
	purchased_date DATE DEFAULT CURRENT_DATE,
	stock_id TEXT NOT NULL,
	price DOUBLE PRECISION,
	open SMALLINT NOT NULL DEFAULT 0 CHECK(open IN (0, 1)),
	opened_date DATE,
	location_id INTEGER,
	shopping_location_id INTEGER,
	note TEXT
);

CREATE TABLE stock_log (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_id INTEGER NOT NULL,
	amount DOUBLE PRECISION NOT NULL,
	best_before_date DATE,
	purchased_date DATE,
	stock_id TEXT NOT NULL,
	transaction_type TEXT NOT NULL,
	price DOUBLE PRECISION,
	undone SMALLINT NOT NULL DEFAULT 0 CHECK(undone IN (0, 1)),
	undone_timestamp TIMESTAMP,
	opened_date DATE,
	location_id INTEGER,
	shopping_location_id INTEGER,
	note TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP)
);

-- quantity_unit_conversions_resolved, copied verbatim from
-- db/pgsql/baseline/03_views_group2.sql:70-280. This is the mechanism ADR-0022 decision 3
-- names as already existing — this spike does not reimplement it, only exercises it.
CREATE VIEW quantity_unit_conversions_resolved AS

WITH RECURSIVE

-- Default QU conversions are handled in a later CTE, as we can't determine yet, for which products they are applicable.
default_conversions(from_qu_id, to_qu_id, factor)
AS (
	SELECT
		from_qu_id,
		to_qu_id,
		factor
	FROM quantity_unit_conversions
	WHERE product_id IS NULL
),

-- First find the closure for all default conversions. This will allow for further pruning when looking for product closure.
default_closure(depth, from_qu_id, to_qu_id, factor, path)
AS (
	-- As a base case, select all available default conversions
	SELECT
		1 AS depth,
		from_qu_id,
		to_qu_id,
		factor,
		'/' || from_qu_id::text || '/' || to_qu_id::text || '/' -- We need to keep track of the conversion path in order to prevent cycles
	FROM default_conversions

	UNION

	-- Recursive case: Find all paths
	SELECT
		c.depth + 1,
		c.from_qu_id,
		s.to_qu_id,
		c.factor * s.factor,
		c.path || s.to_qu_id::text || '/'
	FROM default_closure c
	JOIN default_conversions s
		ON c.to_qu_id = s.from_qu_id
	WHERE c.path NOT LIKE ('%/' || s.to_qu_id::text || '/%') -- Prevent cycles
		AND NOT EXISTS(SELECT 1 FROM default_conversions ci WHERE ci.from_qu_id = c.from_qu_id AND ci.to_qu_id = s.to_qu_id) -- Prune if one of the existing conversions repeats (saves a lot of processing time)

),

default_closure_distinct(from_qu_id, to_qu_id, factor, path)
AS (
	SELECT DISTINCT ON (from_qu_id, to_qu_id)
		from_qu_id,
		to_qu_id,
		factor,
		path
	FROM default_closure
	ORDER BY from_qu_id, to_qu_id, depth
),

product_conversions(product_id, from_qu_id, to_qu_id, factor)
AS (
	-- Priority 1: Product-specific QU overrides
	-- Note that the quantity_unit_conversions table already contains both conversion directions for every conversion.
	SELECT
		product_id,
		from_qu_id,
		to_qu_id,
		factor
	FROM quantity_unit_conversions
	WHERE product_id IS NOT NULL

	UNION

	-- Priority 2: QU conversions with a factor of 1.0 from the stock unit to the stock unit
	SELECT
		id,
		qu_id_stock,
		qu_id_stock,
		1.0::double precision
	FROM products
),

product_closure(depth, product_id, from_qu_id, to_qu_id, factor, path)
AS (
	-- As a base case, select all available product-specific conversions
	SELECT
		1 AS depth,
		product_id,
		from_qu_id,
		to_qu_id,
		factor,
		'/' || from_qu_id::text || '/' || to_qu_id::text || '/' -- We need to keep track of the conversion path in order to prevent cycles
	FROM product_conversions

	UNION

	-- Recursive case: Find all paths
	SELECT
		c.depth + 1,
		c.product_id,
		c.from_qu_id,
		s.to_qu_id,
		c.factor * s.factor,
		c.path || s.to_qu_id::text || '/'
	FROM product_closure c
	JOIN product_conversions s
		ON c.product_id = s.product_id
		AND c.to_qu_id = s.from_qu_id
	WHERE c.path NOT LIKE ('%/' || s.to_qu_id::text || '/%') -- Prevent cycles
		AND NOT EXISTS(SELECT 1 FROM product_conversions ci WHERE ci.product_id = c.product_id AND ci.from_qu_id = c.from_qu_id AND ci.to_qu_id = s.to_qu_id) -- Prune if one of the existing conversions repeats (saves a lot of processing time)
),

product_closure_distinct(product_id, from_qu_id, to_qu_id, factor, path)
AS (
	SELECT DISTINCT ON (product_id, from_qu_id, to_qu_id)
		product_id,
		from_qu_id,
		to_qu_id,
		factor,
		path
	FROM product_closure
	ORDER BY product_id, from_qu_id, to_qu_id, depth
),

-- Now we connect the two closures by adding the reachable conversions from product specific conversions to default conversions
product_reachable(product_id, from_qu_id, to_qu_id, factor, path)
AS (
	SELECT
		product_id,
		from_qu_id,
		to_qu_id,
		factor,
		path
	FROM product_closure_distinct

	UNION

	SELECT
		cd.product_id,
		dcd.from_qu_id,
		dcd.to_qu_id,
		dcd.factor,
		'/' || dcd.from_qu_id::text || '/' || dcd.to_qu_id::text || '/'
	FROM product_closure_distinct cd
	JOIN default_closure_distinct dcd
		ON cd.to_qu_id = dcd.from_qu_id
		OR cd.to_qu_id = dcd.to_qu_id
	WHERE NOT EXISTS(SELECT 1 FROM product_closure_distinct ci WHERE ci.product_id = cd.product_id AND ci.from_qu_id = dcd.from_qu_id AND ci.to_qu_id = dcd.to_qu_id)
),

-- NOTE: no DISTINCT ON / window function is needed here (unlike the two closures above).
-- The only way this UNION can produce duplicate (product_id, from_qu_id, to_qu_id) keys is
-- via the second branch above, where the projected factor/path are taken solely from
-- default_closure_distinct (itself already unique per (from_qu_id, to_qu_id)); any such
-- duplicates are therefore always identical rows, so a plain DISTINCT is sufficient and
-- unambiguous.
product_reachable_distinct(product_id, from_qu_id, to_qu_id, factor, path)
AS (
	SELECT DISTINCT
		product_id,
		from_qu_id,
		to_qu_id,
		factor,
		path
	FROM product_reachable
),

-- Finally we build the combined closure
closure_final(depth, product_id, from_qu_id, to_qu_id, factor, path)
AS (
	-- As a base case, select the product closure
	SELECT
		1 AS depth,
		product_id,
		from_qu_id,
		to_qu_id,
		factor,
		path -- We need to keep track of the conversion path in order to prevent cycles
	FROM product_reachable_distinct

	UNION

	-- Add a default unit conversion to the *end* of the conversion chain
	SELECT
		c.depth + 1,
		c.product_id,
		c.from_qu_id,
		s.to_qu_id,
		c.factor * s.factor,
		c.path || s.to_qu_id::text || '/'
	FROM closure_final c
	JOIN product_reachable_distinct s
		ON c.product_id = s.product_id
		AND c.to_qu_id = s.from_qu_id
	WHERE c.path NOT LIKE ('%/' || s.to_qu_id::text || '/%') -- Prevent cycles
		AND NOT EXISTS(SELECT 1 FROM product_reachable_distinct ci WHERE ci.product_id = c.product_id AND ci.from_qu_id = c.from_qu_id AND ci.to_qu_id = s.to_qu_id) -- Prune (if already exists)
)

SELECT DISTINCT ON (c.product_id, c.from_qu_id, c.to_qu_id)
	-1 AS id, -- Dummy, LessQL needs an id column
	c.product_id,
	c.from_qu_id,
	qu_from.name AS from_qu_name,
	qu_from.name_plural AS from_qu_name_plural,
	c.to_qu_id,
	qu_to.name AS to_qu_name,
	qu_to.name_plural AS to_qu_name_plural,
	c.factor,
	c.path
FROM closure_final c
JOIN quantity_units qu_from
	ON c.from_qu_id = qu_from.id
JOIN quantity_units qu_to
	ON c.to_qu_id = qu_to.id
ORDER BY c.product_id, c.from_qu_id, c.to_qu_id, c.depth;
