-- SPIKE ONLY (ADR-0036 feasibility). Not a migration; no number is reserved for it.
-- Applied to a disposable schema that has already been migrated to HEAD.

CREATE TABLE stock_row_lots (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	stock_row_id INTEGER NOT NULL REFERENCES stock (id) ON DELETE CASCADE,
	-- NULL = the unattributed pool: quantity in the row whose lot is unknown.
	lot_id INTEGER REFERENCES stock_log (id) ON DELETE CASCADE,
	amount DOUBLE PRECISION NOT NULL CHECK (amount > 0),
	basis TEXT NOT NULL CHECK (basis IN ('recorded', 'derived', 'unknown')),
	UNIQUE NULLS NOT DISTINCT (stock_row_id, lot_id),
	CHECK ((lot_id IS NULL) = (basis = 'unknown'))
);
CREATE INDEX ix_stock_row_lots_lot ON stock_row_lots (lot_id);

CREATE TABLE stock_booking_lots (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	booking_id INTEGER NOT NULL REFERENCES stock_log (id) ON DELETE CASCADE,
	lot_id INTEGER REFERENCES stock_log (id) ON DELETE CASCADE,
	amount DOUBLE PRECISION NOT NULL CHECK (amount <> 0),
	basis TEXT NOT NULL CHECK (basis IN ('recorded', 'derived', 'unknown')),
	UNIQUE NULLS NOT DISTINCT (booking_id, lot_id),
	-- A NULL lot is a recorded draw on the unattributed pool; an 'unknown' basis marks an
	-- addition whose units were merged before tracking and cannot be located (lot_id = booking).
	CHECK (lot_id IS NOT NULL OR basis = 'recorded')
);
CREATE INDEX ix_stock_booking_lots_lot ON stock_booking_lots (lot_id, booking_id);

-- Tolerance of ADR-0032 decision 1.
CREATE FUNCTION spike_tol(a double precision, b double precision) RETURNS double precision
LANGUAGE sql IMMUTABLE AS $$ SELECT GREATEST(1e-9, 1e-12 * GREATEST(abs(a), abs(b))) $$;

-- Backfill classification (spike form of the migration step). Idempotent: it only writes
-- contributions for stock rows that have none and allocations for bookings that have none, so
-- a second run changes nothing. p_product limits the scope to one product (used by the lazy
-- path and by batching). Writes nothing to stock, stock_log or stock_entry_origins.
CREATE FUNCTION spike_backfill(p_product integer DEFAULT NULL)
RETURNS TABLE (family_class text, families bigint, stock_rows bigint)
LANGUAGE plpgsql AS $$
BEGIN
	DROP TABLE IF EXISTS _fam; DROP TABLE IF EXISTS _stat; DROP TABLE IF EXISTS _lot;

	CREATE TEMP TABLE _fam AS
	WITH ids AS (
		SELECT product_id, stock_id FROM stock WHERE (p_product IS NULL OR product_id = p_product)
		UNION
		SELECT product_id, stock_id FROM stock_log WHERE (p_product IS NULL OR product_id = p_product)
	)
	SELECT i.product_id, i.stock_id, COALESCE(o.origin_stock_id, i.stock_id) AS root
	FROM ids i LEFT JOIN stock_entry_origins o ON o.stock_id = i.stock_id;
	CREATE INDEX ON _fam (product_id, root);
	CREATE INDEX ON _fam (stock_id);

	CREATE TEMP TABLE _stat AS
	WITH live AS (
		SELECT f.product_id, f.root, l.id, l.amount,
			(l.transaction_type IN ('purchase', 'self-production', 'inventory-correction') AND l.amount > 0) AS is_add,
			CASE l.transaction_type
				WHEN 'purchase' THEN l.amount WHEN 'self-production' THEN l.amount
				WHEN 'inventory-correction' THEN l.amount WHEN 'consume' THEN l.amount
				WHEN 'transfer_from' THEN l.amount WHEN 'transfer_to' THEN l.amount
				WHEN 'stock-edit-new' THEN l.amount WHEN 'stock-edit-old' THEN -l.amount
				ELSE 0 END AS delta
		FROM stock_log l JOIN _fam f ON f.stock_id = l.stock_id AND f.product_id = l.product_id
		WHERE l.undone = 0
	), b AS (
		SELECT product_id, root,
			count(*) FILTER (WHERE is_add) AS n_add,
			COALESCE(sum(amount) FILTER (WHERE is_add), 0) AS sum_add,
			count(*) FILTER (WHERE NOT is_add) AS n_other,
			COALESCE(sum(delta), 0) AS delta_sum
		FROM live GROUP BY product_id, root
	), r AS (
		SELECT f.product_id, f.root, count(s.id) AS n_rows, COALESCE(sum(s.amount), 0) AS rows_sum
		FROM _fam f LEFT JOIN stock s ON s.stock_id = f.stock_id AND s.product_id = f.product_id
		GROUP BY f.product_id, f.root
	)
	SELECT r.product_id, r.root, COALESCE(b.n_add, 0) AS n_add, COALESCE(b.n_other, 0) AS n_other,
		COALESCE(b.sum_add, 0) AS sum_add, COALESCE(b.delta_sum, 0) AS delta_sum, r.n_rows, r.rows_sum,
		CASE
			WHEN COALESCE(b.n_add, 0) = 0 AND r.n_rows = 0 THEN 'N'
			WHEN COALESCE(b.n_add, 0) = 1 AND abs(COALESCE(b.delta_sum, 0) - r.rows_sum) <= spike_tol(COALESCE(b.delta_sum, 0), r.rows_sum) THEN 'E'
			WHEN COALESCE(b.n_add, 0) >= 2 AND COALESCE(b.n_other, 0) = 0 AND r.n_rows = 1
				AND abs(b.sum_add - r.rows_sum) <= spike_tol(b.sum_add, r.rows_sum) THEN 'X'
			ELSE 'U' END AS class
	FROM r LEFT JOIN b ON b.product_id = r.product_id AND b.root = r.root;
	CREATE INDEX ON _stat (product_id, root);

	-- The lots of each tracked family: the live additions (undone additions are lots too, with
	-- no contribution, but only live ones are candidates for E and X).
	CREATE TEMP TABLE _lot AS
	SELECT st.product_id, st.root, st.class, l.id AS lot_id, l.amount AS lot_amount
	FROM _stat st
	JOIN _fam f ON f.product_id = st.product_id AND f.root = st.root
	JOIN stock_log l ON l.stock_id = f.stock_id AND l.product_id = f.product_id
	WHERE l.undone = 0 AND l.amount > 0 AND l.transaction_type IN ('purchase', 'self-production', 'inventory-correction')
		AND st.class IN ('E', 'X');
	CREATE INDEX ON _lot (product_id, root);

	INSERT INTO stock_row_lots (stock_row_id, lot_id, amount, basis)
	SELECT s.id, lo.lot_id, CASE WHEN st.class = 'E' THEN s.amount ELSE lo.lot_amount END, 'derived'
	FROM stock s
	JOIN _fam f ON f.stock_id = s.stock_id AND f.product_id = s.product_id
	JOIN _stat st ON st.product_id = f.product_id AND st.root = f.root
	JOIN _lot lo ON lo.product_id = st.product_id AND lo.root = st.root
	WHERE s.amount > 0 AND NOT EXISTS (SELECT 1 FROM stock_row_lots e WHERE e.stock_row_id = s.id);

	INSERT INTO stock_row_lots (stock_row_id, lot_id, amount, basis)
	SELECT s.id, NULL, s.amount, 'unknown'
	FROM stock s
	JOIN _fam f ON f.stock_id = s.stock_id AND f.product_id = s.product_id
	JOIN _stat st ON st.product_id = f.product_id AND st.root = f.root
	WHERE st.class = 'U' AND s.amount > 0 AND NOT EXISTS (SELECT 1 FROM stock_row_lots e WHERE e.stock_row_id = s.id);

	-- Bookings. Class E: every booking of the family, live or undone, against the one live lot
	-- (additions against themselves). Classes X and U: only the additions, as derived (X) or
	-- unknown (U) lots. Nothing else is invented.
	INSERT INTO stock_booking_lots (booking_id, lot_id, amount, basis)
	SELECT l.id,
		CASE WHEN l.amount > 0 AND l.transaction_type IN ('purchase', 'self-production', 'inventory-correction') THEN l.id
			ELSE (SELECT lo.lot_id FROM _lot lo WHERE lo.product_id = st.product_id AND lo.root = st.root) END,
		l.amount,
		CASE WHEN st.class IN ('E', 'X') THEN 'derived' ELSE 'unknown' END
	FROM stock_log l
	JOIN _fam f ON f.stock_id = l.stock_id AND f.product_id = l.product_id
	JOIN _stat st ON st.product_id = f.product_id AND st.root = f.root
	WHERE l.amount <> 0 AND st.class <> 'N'
		AND NOT EXISTS (SELECT 1 FROM stock_booking_lots e WHERE e.booking_id = l.id)
		AND (st.class = 'E' OR (l.amount > 0 AND l.transaction_type IN ('purchase', 'self-production', 'inventory-correction')));

	RETURN QUERY SELECT s.class, count(*)::bigint, COALESCE(sum(s.n_rows), 0)::bigint FROM _stat s GROUP BY s.class;
	DROP TABLE _fam; DROP TABLE _stat; DROP TABLE _lot;
END $$;
