-- Plan 25 group B. Absolute clocks use TIMESTAMPTZ, as in 0269.
-- Plain tables: templates/artifacts and job readiness columns belong to plan 27.
-- The two credential tables implement ADR-0019's durable sessions and pending rotations
-- without widening api_keys. No print-history foreign key reaches labels or locations.
CREATE TABLE label_workers (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL UNIQUE, description TEXT,
 configuration_mode TEXT NOT NULL CHECK (configuration_mode IN ('declared','paired')),
 active SMALLINT NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
 last_registered_at TIMESTAMPTZ,
 requires_repairing SMALLINT NOT NULL DEFAULT 0 CHECK (requires_repairing IN (0,1))
);
CREATE TABLE label_drivers (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 driver_id TEXT NOT NULL, schema_version TEXT NOT NULL,
 contract_version INTEGER NOT NULL CHECK (contract_version = 1),
 connection_types JSONB NOT NULL, discriminator_properties JSONB NOT NULL,
 combination_binding JSONB NOT NULL, settings_schemas JSONB NOT NULL,
 capability_document JSONB NOT NULL,
 registered_by_worker_id INTEGER NOT NULL REFERENCES label_workers(id),
 UNIQUE (driver_id, schema_version)
);
CREATE TABLE label_worker_capabilities (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 worker_id INTEGER NOT NULL REFERENCES label_workers(id),
 driver_id TEXT NOT NULL, schema_version TEXT NOT NULL,
 artifact_forms JSONB NOT NULL, profile_contract_versions JSONB NOT NULL,
 last_registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE (worker_id, driver_id, schema_version),
 FOREIGN KEY (driver_id, schema_version) REFERENCES label_drivers(driver_id, schema_version)
);
CREATE TABLE label_printers (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL, description TEXT,
 active SMALLINT NOT NULL DEFAULT 1 CHECK (active IN (0,1)),
 is_default SMALLINT NOT NULL DEFAULT 0 CHECK (is_default IN (0,1)),
 worker_id INTEGER NOT NULL REFERENCES label_workers(id),
 driver_id TEXT NOT NULL, driver_schema_version TEXT NOT NULL,
 connection TEXT NOT NULL, connection_type TEXT NOT NULL, model TEXT NOT NULL,
 settings JSONB NOT NULL, settings_validated_at TIMESTAMPTZ NOT NULL,
 FOREIGN KEY (driver_id, driver_schema_version) REFERENCES label_drivers(driver_id, schema_version)
);
CREATE UNIQUE INDEX label_printers_one_default ON label_printers(is_default) WHERE is_default = 1;
CREATE TABLE label_printer_status (
 printer_id INTEGER PRIMARY KEY REFERENCES label_printers(id),
 reported_by_worker_id INTEGER NOT NULL REFERENCES label_workers(id),
 last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 reported_media JSONB, device_state TEXT, error_state JSONB, warning_state JSONB,
 raw_report JSONB NOT NULL
);
CREATE TABLE print_jobs (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 outbox_id INTEGER NOT NULL UNIQUE REFERENCES outbox(id),
 printer_id INTEGER NOT NULL, label_uid TEXT NOT NULL,
 attempts_authorized INTEGER NOT NULL DEFAULT 1 CHECK (attempts_authorized > 0),
 attempts_made INTEGER NOT NULL DEFAULT 0 CHECK (attempts_made >= 0),
 current_attempt_id INTEGER,
 outcome TEXT CHECK (outcome IN ('printed','sent','dead_lettered')),
 outcome_at TIMESTAMPTZ,
 CHECK (attempts_made <= attempts_authorized)
);
CREATE INDEX print_jobs_claimable ON print_jobs(printer_id, outbox_id) WHERE outcome IS NULL;
CREATE TABLE print_attempts (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 outbox_id INTEGER NOT NULL REFERENCES outbox(id),
 job_id INTEGER NOT NULL REFERENCES print_jobs(id),
 attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
 worker_id INTEGER NOT NULL REFERENCES label_workers(id),
 claimed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 lease_expires_at TIMESTAMPTZ NOT NULL, lease_hard_deadline TIMESTAMPTZ NOT NULL,
 heartbeats INTEGER NOT NULL DEFAULT 0 CHECK (heartbeats >= 0),
 bytes_sent_at TIMESTAMPTZ, device_reported_at TIMESTAMPTZ, ended_at TIMESTAMPTZ,
 outcome TEXT CHECK (outcome IN ('printed','sent','failed','blocked','uncertain')),
 acknowledged_on TEXT NOT NULL CHECK (acknowledged_on IN ('report','send')),
 error_text TEXT, reported_outcome TEXT CHECK (reported_outcome IN ('printed','failed')),
 reported_at TIMESTAMPTZ, reported_detail JSONB, superseded_at TIMESTAMPTZ,
 UNIQUE (outbox_id, attempt_number),
 CHECK (lease_expires_at <= lease_hard_deadline)
);
ALTER TABLE print_jobs ADD FOREIGN KEY (current_attempt_id) REFERENCES print_attempts(id);
CREATE TABLE print_evidence (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 attempt_id INTEGER NOT NULL REFERENCES print_attempts(id),
 submission_id TEXT NOT NULL, evidence_type TEXT NOT NULL, source TEXT NOT NULL,
 observed_at TIMESTAMPTZ NOT NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 decoded_uid TEXT, printer_status JSONB, image_ref TEXT CHECK (image_ref !~ '://'),
 confidence DOUBLE PRECISION CHECK (confidence BETWEEN 0 AND 1), detail JSONB NOT NULL,
 UNIQUE (source, submission_id)
);
CREATE TABLE label_worker_sessions (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 worker_id INTEGER NOT NULL REFERENCES label_workers(id),
 created_by_user_id INTEGER NOT NULL,
 pairing_material_hash TEXT, material_expires_at TIMESTAMPTZ, material_consumed_at TIMESTAMPTZ,
 started_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ,
 revoked_reason TEXT CHECK (revoked_reason IN ('admin','credential_reuse','worker_deactivated'))
);
CREATE UNIQUE INDEX label_worker_pairing_material ON label_worker_sessions(pairing_material_hash) WHERE pairing_material_hash IS NOT NULL;
CREATE TABLE label_worker_credentials (
 api_key_id INTEGER PRIMARY KEY REFERENCES api_keys(id),
 worker_id INTEGER NOT NULL REFERENCES label_workers(id),
 session_id INTEGER REFERENCES label_worker_sessions(id),
 issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, consumed_at TIMESTAMPTZ,
 rotation_request_id TEXT, rotation_material_hash TEXT,
 successor_api_key_id INTEGER REFERENCES api_keys(id),
 UNIQUE (worker_id, rotation_request_id)
);
