-- Plan 27 group A: the template document, its lifecycle, its assets, and media profiles.
--
-- ADR-0021 makes the label template application data rather than something a worker
-- registers, so these five tables are Victual's. They are plain tables with no views and no
-- triggers, for the same reason plan 25's 0270 is: what enforces the rules here is the
-- application, and a trigger that duplicated one of them would be a second place for it to
-- drift.
--
-- PostgreSQL-only, above the 0265 SQLite freeze. TIMESTAMPTZ throughout, matching 0269 and
-- 0270 rather than the baseline's local TIMESTAMP: a publication instant and a preview
-- expiry are absolute instants.
--
-- Group B (0272) holds captures, render requests, artifacts and idempotency keys, and
-- alters print_jobs. It is a second number because it references this one.

-- Template identity. The document itself lives in a draft and in published versions; this
-- row is the name, the entity kind it captures for, and the administrative pointer.
CREATE TABLE label_templates (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	entity_kind TEXT NOT NULL CHECK (entity_kind IN ('location', 'product', 'stock_entry')),
	default_version_id INTEGER,
	archived_at TIMESTAMPTZ,
	row_created_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One mutable draft per template, carrying the revision token that makes a concurrent edit
-- a conflict rather than a silent overwrite of somebody else's work.
CREATE TABLE label_template_drafts (
	template_id INTEGER PRIMARY KEY REFERENCES label_templates (id) ON DELETE CASCADE,
	document JSONB NOT NULL,
	revision_token TEXT NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by_user_id INTEGER
);

-- Published versions are immutable. There is no UPDATE path in the service and no trigger
-- forbidding one: the digest is what makes a rewrite detectable, and a rewritten row would
-- be caught by every artifact manifest that names the old digest.
--
-- document_digest is SHA-256 over the RFC 8785 canonical encoding of the document
-- (helpers/CanonicalJson.php), never over whatever byte order json_encode produced.
CREATE TABLE label_template_versions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	template_id INTEGER NOT NULL REFERENCES label_templates (id),
	version INTEGER NOT NULL CHECK (version >= 1),
	document JSONB NOT NULL,
	document_digest TEXT NOT NULL CHECK (document_digest ~ '^[0-9a-f]{64}$'),
	asset_ids JSONB NOT NULL,
	required_capabilities JSONB NOT NULL,
	published_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	published_by_user_id INTEGER,
	UNIQUE (template_id, version)
);

CREATE INDEX label_template_versions_template ON label_template_versions (template_id, version DESC);

ALTER TABLE label_templates ADD CONSTRAINT label_templates_default_version
	FOREIGN KEY (default_version_id) REFERENCES label_template_versions (id);

-- Fonts and raster images. The bytes are in `files` under a group deliberately absent from
-- the OpenAPI FileGroups enum, so FilesApiController refuses them by the check it already
-- runs and the only path to them is this subsystem's own authorized endpoints (plan 27
-- piece 5, and sweep finding S32).
--
-- content_digest is over the exact bytes, not over a document: an asset is bytes.
CREATE TABLE label_assets (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	asset_kind TEXT NOT NULL CHECK (asset_kind IN ('font', 'image')),
	mime_type TEXT NOT NULL,
	byte_length BIGINT NOT NULL CHECK (byte_length > 0),
	content_digest TEXT NOT NULL UNIQUE CHECK (content_digest ~ '^[0-9a-f]{64}$'),
	file_group TEXT NOT NULL,
	file_name TEXT NOT NULL,
	-- Decoded facts, recorded because they were checked on decode rather than believed from
	-- a declared type: an image's real dimensions, a font's real family and style.
	width_px INTEGER,
	height_px INTEGER,
	font_family TEXT,
	font_style TEXT,
	licence TEXT NOT NULL,
	licence_notice TEXT,
	row_created_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CHECK ((asset_kind = 'image' AND width_px IS NOT NULL AND height_px IS NOT NULL)
		OR (asset_kind = 'font' AND font_family IS NOT NULL)),
	UNIQUE (file_group, file_name)
);

-- An immutable, versioned, digested contract derived from a printer's validated
-- capabilities, and deliberately not the printer row: the printer's address changes and its
-- media is reconfigured, while a profile a job was rendered against cannot.
--
-- dpi_x and dpi_y are separate columns because they differ on real hardware - a 600 dpi
-- Brother QL is 600 along the feed and 300 across it - and because a single dpi invites
-- every caller to assume they are equal, which is the defect issue #90 is made of.
CREATE TABLE label_media_profiles (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	profile_key TEXT NOT NULL,
	version INTEGER NOT NULL CHECK (version >= 1),
	driver_id TEXT NOT NULL,
	driver_schema_version TEXT NOT NULL,
	model TEXT NOT NULL,
	media TEXT NOT NULL,
	connection_type TEXT NOT NULL,
	color_mode TEXT NOT NULL,
	dpi_x INTEGER NOT NULL CHECK (dpi_x > 0),
	dpi_y INTEGER NOT NULL CHECK (dpi_y > 0),
	raster_width_px INTEGER NOT NULL CHECK (raster_width_px > 0),
	document JSONB NOT NULL,
	document_digest TEXT NOT NULL CHECK (document_digest ~ '^[0-9a-f]{64}$'),
	row_created_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (profile_key, version),
	FOREIGN KEY (driver_id, driver_schema_version)
		REFERENCES label_drivers (driver_id, schema_version)
);

CREATE INDEX label_media_profiles_key ON label_media_profiles (profile_key, version DESC);
