-- Plan 27 group B: captures, durable render requests, artifacts and idempotency, plus the
-- alteration to plan 25's print_jobs that finally gives a job an artifact to carry.
--
-- This is the number that turns plan 25 group B's fail-closed readiness seam into a real
-- condition. Until it lands, PrintAttemptService::ArtifactReady() answers false for every
-- job and no worker is ever offered work; after it, the condition is that a validated
-- artifact is attached, which is what ADR-0019 decision item 4 and ADR-0021 require and is
-- the boundary the maintainer chose to keep closed rather than open early.
--
-- PostgreSQL-only, TIMESTAMPTZ throughout, plain tables.

-- What was captured, when, and under which formatting inputs. Immutable once written:
-- re-rendering a capture later has to produce the same label, which it cannot do if the
-- locale or the timezone is read from the host at render time.
--
-- Clients submit entity references and never purported values (plan 27 piece 2), so every
-- row here was authorized and read by Victual in one transaction.
CREATE TABLE label_captures (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	entity_kind TEXT NOT NULL CHECK (entity_kind IN ('location', 'product', 'stock_entry')),
	target_id BIGINT,
	label_uid TEXT,
	captured_fields JSONB NOT NULL,
	locale TEXT NOT NULL,
	timezone TEXT NOT NULL,
	is_sample SMALLINT NOT NULL DEFAULT 0 CHECK (is_sample IN (0, 1)),
	digest TEXT NOT NULL CHECK (digest ~ '^[0-9a-f]{64}$'),
	captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	captured_by_user_id INTEGER,
	-- A sample capture names no target and no uid; a real one names both. Stated as a
	-- constraint because a sample that acquired a uid could be promoted to a print.
	CHECK ((is_sample = 1 AND target_id IS NULL AND label_uid IS NULL)
		OR (is_sample = 0 AND target_id IS NOT NULL))
);

CREATE INDEX label_captures_uid ON label_captures (label_uid) WHERE label_uid IS NOT NULL;

-- The durable render request. It exists before any renderer does, which is the property
-- plan 27 piece 4 asks for: no request may depend on a live Victual process remembering to
-- launch something.
--
-- The lease and the generation token fence competing renderers against each other. They are
-- deliberately *not* the print attempt's fence: an expired render may be retried
-- automatically precisely because a renderer cannot touch a printer, and that is the one
-- place in this subsystem where automatic retry is allowed.
CREATE TABLE label_render_requests (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	purpose TEXT NOT NULL CHECK (purpose IN ('production', 'preview_live', 'preview_sample', 'preview_draft')),
	template_version_id INTEGER REFERENCES label_template_versions (id),
	draft_document JSONB,
	draft_template_id INTEGER REFERENCES label_templates (id),
	profile_id INTEGER NOT NULL REFERENCES label_media_profiles (id),
	capture_id INTEGER NOT NULL REFERENCES label_captures (id),
	state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'rendering', 'ready', 'invalid', 'failed')),
	generation INTEGER NOT NULL DEFAULT 0 CHECK (generation >= 0),
	generation_token TEXT,
	lease_expires_at TIMESTAMPTZ,
	attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
	error_code TEXT,
	error_element TEXT,
	error_detail TEXT,
	artifact_id INTEGER,
	expires_at TIMESTAMPTZ,
	row_created_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by_user_id INTEGER,
	-- A draft preview pins a snapshot of the document so a later edit cannot change an
	-- in-flight result; every other purpose renders a published version.
	CHECK ((purpose = 'preview_draft' AND draft_document IS NOT NULL AND draft_template_id IS NOT NULL AND template_version_id IS NULL)
		OR (purpose <> 'preview_draft' AND draft_document IS NULL AND template_version_id IS NOT NULL))
);

CREATE INDEX label_render_requests_queued ON label_render_requests (id)
	WHERE state IN ('pending', 'rendering');
CREATE INDEX label_render_requests_expiring ON label_render_requests (expires_at)
	WHERE expires_at IS NOT NULL;

-- Immutable bytes plus a manifest. The bytes live in `files` under a group deliberately
-- absent from the OpenAPI FileGroups enum; byte_digest covers the exact bytes and
-- manifest_digest covers the RFC 8785 canonical encoding of the manifest.
--
-- retention_class is what promotion changes: an unpromoted preview expires after 24 hours,
-- a retained artifact lives until its label is retired, because that is what makes an exact
-- reprint possible at all.
CREATE TABLE label_artifacts (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	render_request_id INTEGER NOT NULL REFERENCES label_render_requests (id),
	form TEXT NOT NULL,
	byte_digest TEXT NOT NULL CHECK (byte_digest ~ '^[0-9a-f]{64}$'),
	byte_length BIGINT NOT NULL CHECK (byte_length > 0),
	mime_type TEXT NOT NULL,
	width_px INTEGER NOT NULL CHECK (width_px > 0),
	height_px INTEGER NOT NULL CHECK (height_px > 0),
	dpi_x INTEGER NOT NULL CHECK (dpi_x > 0),
	dpi_y INTEGER NOT NULL CHECK (dpi_y > 0),
	color_mode TEXT NOT NULL,
	profile_id INTEGER NOT NULL REFERENCES label_media_profiles (id),
	template_version_id INTEGER REFERENCES label_template_versions (id),
	capture_id INTEGER NOT NULL REFERENCES label_captures (id),
	renderer_id TEXT NOT NULL,
	renderer_version TEXT NOT NULL,
	manifest JSONB NOT NULL,
	manifest_digest TEXT NOT NULL CHECK (manifest_digest ~ '^[0-9a-f]{64}$'),
	file_group TEXT NOT NULL,
	file_name TEXT NOT NULL,
	retention_class TEXT NOT NULL DEFAULT 'preview' CHECK (retention_class IN ('preview', 'retained')),
	collected_at TIMESTAMPTZ,
	row_created_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (file_group, file_name)
);

CREATE INDEX label_artifacts_request ON label_artifacts (render_request_id);
CREATE INDEX label_artifacts_collectable ON label_artifacts (retention_class, row_created_timestamp)
	WHERE collected_at IS NULL;

ALTER TABLE label_render_requests ADD CONSTRAINT label_render_requests_artifact
	FOREIGN KEY (artifact_id) REFERENCES label_artifacts (id);

-- Idempotency is scoped to a principal and an operation and bound to a canonical
-- fingerprint of the request, so the same key with changed inputs is a conflict rather than
-- a replay. The stored response is what a replay returns, after authorization is rechecked.
CREATE TABLE label_idempotency_keys (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	principal_user_id INTEGER NOT NULL,
	operation TEXT NOT NULL,
	idempotency_key TEXT NOT NULL,
	request_fingerprint TEXT NOT NULL CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
	resource_kind TEXT,
	resource_id INTEGER,
	response JSONB,
	expires_at TIMESTAMPTZ NOT NULL,
	row_created_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (principal_user_id, operation, idempotency_key)
);

CREATE INDEX label_idempotency_keys_expiring ON label_idempotency_keys (expires_at);

-- The alteration plan 27's migration inventory names. A job now records which operation
-- created it, the artifact it carries and the render request that produced it, the job a
-- reprint replays, and the idempotency key that guarded its creation.
--
-- artifact_id is the readiness condition. It is nullable because a job legitimately exists
-- while its render is pending; what changes is that a job with no artifact is not claimable,
-- which is enforced in the claim query rather than by a constraint here.
ALTER TABLE print_jobs ADD COLUMN operation TEXT NOT NULL DEFAULT 'issue'
	CHECK (operation IN ('issue', 'reprint', 'revised_print', 'promote_preview'));
ALTER TABLE print_jobs ADD COLUMN artifact_id INTEGER REFERENCES label_artifacts (id);
ALTER TABLE print_jobs ADD COLUMN render_request_id INTEGER REFERENCES label_render_requests (id);
ALTER TABLE print_jobs ADD COLUMN capture_id INTEGER REFERENCES label_captures (id);
ALTER TABLE print_jobs ADD COLUMN source_job_id INTEGER REFERENCES print_jobs (id);
ALTER TABLE print_jobs ADD COLUMN idempotency_key_id INTEGER REFERENCES label_idempotency_keys (id);
ALTER TABLE print_jobs ADD COLUMN cancelled_at TIMESTAMPTZ;
ALTER TABLE print_jobs ADD COLUMN cancelled_reason TEXT;

-- The claim index gains the readiness column, so the predicate the claim query actually
-- runs is the predicate the index covers. The old index is dropped rather than left beside
-- it: two partial indexes over the same rows for the same query is a planner coin toss.
DROP INDEX print_jobs_claimable;
CREATE INDEX print_jobs_claimable ON print_jobs (printer_id, outbox_id)
	WHERE outcome IS NULL AND cancelled_at IS NULL AND artifact_id IS NOT NULL;

-- A cancelled job is not claimable and is not an outcome: it never printed, and recording
-- it as `printed` or `dead_lettered` would say something untrue about a physical object.
ALTER TABLE print_jobs ADD CONSTRAINT print_jobs_cancellation
	CHECK ((cancelled_at IS NULL) = (cancelled_reason IS NULL));
