<?php

// This is executed inside DatabaseMigrationService class/context

use Victual\Services\DatabaseService;
use Victual\Services\LocalizationService;

// Storage classes for locations: how cold a location is kept, not merely whether it is a
// freezer. See docs/plans/23-storage-classes.md and issue #127.
//
// WHY ONE PHP FILE RATHER THAN A .pgsql.sql SCHEMA MIGRATION PLUS A DATA MIGRATION LIKE
// 0263/0264. ADR-0003 puts seed data in PHP rather than SQL literals, because the five
// names have to go through LocalizationService the way migrations/0031.php's default
// location and quantity units do - "Ambient" is not the same string in every configured
// locale, and could not be a literal even if this migration wanted it to be. 0263/0264
// split a column from its backfill because the column had to exist before the backfill
// could run against real rows; here the "backfill" is five constant rows with no
// dependency on anything already in the table, so there is nothing to gain by splitting
// them into two numbers. The plan asks for the small kind of migration and names one file.
//
// WHY NO VIEW AND NO TRIGGER. locations_resolved (migrations/0273.pgsql.sql) already
// carries every column of `locations` through unchanged, so the class rides along with the
// rest of the row and needs no view of its own. Per plan 23 question 2's answer,
// `is_freezer`'s derivation from the class lives in the application write path
// (GenericEntityApiController), not a trigger: the importer this fork inherited from
// upstream grocy has no storage-class concept at all, so every imported location arrives
// with a NULL class, and under question 1's answer a NULL class leaves `is_freezer`
// exactly as it came in - there is nothing for a trigger to derive, because the one case
// that would have justified one cannot occur.
//
// WHY storage_class_id CARRIES A FOREIGN KEY WHEN parent_location_id DOES NOT.
// `0273.pgsql.sql` explains at length why that column has none: a self-referential tree
// needs its own cycle/depth guards regardless of what a FOREIGN KEY could check, so the
// constraint would buy nothing there. A class reference is ordinary lookup data with no
// such argument against it, so it gets the same FOREIGN KEY every other master-data
// reference this fork's own migrations (0270-0272) added carries.
//
// WHY THE TEMPERATURES ARE NUMERIC AND STORED AT ALL. Question 4's answer keeps them
// structured, even though nothing in v1 resolves a class from a temperature, because a
// wine cooler and a cheese cave differ by *set point* and plan 22's excursion handling
// wants to compare an observed temperature against a range later. A range stored as two
// numbers is ready for that; a range encoded in a name is not.
//
// WHY THIS TABLE IS ENGINE-EXCLUSIVE WITH NO @engine-exclusive MARKER. Above
// DatabaseMigrationService::SQLITE_FROZEN_MIGRATION_ID (0265) a new table exists on
// PostgreSQL and nowhere else, not because SQLite needs no change but because there is no
// longer a file that could give it one - db/pgsql/README.md's "above the freeze" section.
// So `storage_classes` is named in `.devtools/pgsql/migratedifftest.php`'s
// ENGINE_EXCLUSIVE_TABLES rather than carrying the marker check-migrations.php asks for
// only below the freeze.

$db = DatabaseService::GetInstance()->GetDbConnectionRaw();

$db->exec(<<<'SQL'
	CREATE TABLE storage_classes (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name TEXT NOT NULL UNIQUE,
		min_temp_c NUMERIC,
		max_temp_c NUMERIC,
		treats_as_freezer SMALLINT NOT NULL DEFAULT 0 CHECK(treats_as_freezer IN (0, 1)),
		sort_order INTEGER NOT NULL DEFAULT 0,
		row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
		active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
	)
	SQL);

// Nullable and additive: NULL means unclassified, which is what every existing location
// means today and therefore what this migration leaves every row as - no behavioural
// change on upgrade. See plan 23 question 3.
$db->exec('ALTER TABLE locations ADD COLUMN storage_class_id INTEGER REFERENCES storage_classes(id)');

// Seeded per ADR-0003, in the order the location form's picker should offer them - coldest
// to warmest, which is also `sort_order`. The ranges are the plan's own starting figures;
// they are metadata a user can edit or extend, not a claim this fork verifies against any
// sensor.
$localizationService = LocalizationService::GetInstance(VICTUAL_DEFAULT_LOCALE);

$insert = $db->prepare('INSERT INTO storage_classes
	(name, min_temp_c, max_temp_c, treats_as_freezer, sort_order) VALUES (?, ?, ?, ?, ?)');

foreach ([
	[$localizationService->__t('Deep freeze'), -40, -18, 1],
	[$localizationService->__t('Freezer'), -18, -12, 1],
	[$localizationService->__t('Fridge'), 2, 8, 0],
	[$localizationService->__t('Cooler'), 8, 15, 0],
	[$localizationService->__t('Ambient'), 15, 25, 0],
] as $sortOrder => [$name, $minTempC, $maxTempC, $treatsAsFreezer])
{
	$insert->execute([$name, $minTempC, $maxTempC, $treatsAsFreezer, $sortOrder]);
}
