-- Directed substitution between products (plan 31, issue 125): "A can be used where B is
-- called for" is a directed edge, one product to another, for the pairs ADR-0023's catalogue
-- sampling made separate products with no shared parent -- whole beans and ground coffee,
-- a block of cheddar and shredded, unsalted butter and salted. Today's only substitution
-- mechanism, products_current_substitutions, is entirely a view over products_resolved (the
-- parent/child mapping); with beans and grounds modelled as separate products there is no
-- parent to hang a substitution off, so the relationship has nowhere to live. See
-- docs/plans/31-directed-substitution.md,
-- docs/adr/0023-taxonomy-is-groups-packaging-is-parent-product.md (decision 4, accepted
-- 2026-09-14) and issue 125.
--
-- SCOPE DECIDED HERE, against the plan's four open questions -- none of them gated the start,
-- per the issue's own scheduling comment, so each is answered and recorded rather than left
-- for a later PR to discover the schema already assumed one way:
--
--   Q1 (quantity factor) -- NO. The plan names its own precedent for this
--      (ADR-0022 decision 3: refuse rather than approximate a conversion that is right
--      sometimes). A factor that holds for coffee (1:1 by weight) and not for herbs (a
--      tablespoon of fresh is a teaspoon of dried) is worse than no factor at all. An edge is
--      the bare (from, to) pair.
--
--   Q2 (transitivity) -- NO, not in this migration. Whole -> cracked -> ground is a plausible
--      chain, and a recursive closure is cheap here (the pattern is already load-bearing three
--      times over: quantity_unit_conversions_resolved, locations_resolved,
--      product_groups_resolved) -- but a transitive closure over an arbitrary directed graph
--      needs cycle protection an acyclic hierarchy does not (A -> B and B -> A can both be
--      true here without contradiction; a tree's parent pointers cannot do that), and nothing
--      in the plan's verification list requires it beyond asserting a chain is *not* offered.
--      product_substitutions_resolved below is direct edges only; the chain case in the new
--      suite phase asserts the non-transitive answer.
--
--   Q3 (counts toward minimum stock) -- NO, unchanged from today. stock_missing_products
--      (db/pgsql/baseline/05_views_l2.sql) never joins products_current_substitutions, so a
--      sub product in stock already does not satisfy its parent's min_stock_amount -- adding a
--      directed edge that did so would be a new, inconsistent exception rather than a
--      preserved behaviour. Left for a follow-on together with Q1-3 of plan 30, which the same
--      view would need to change to answer.
--
--   Q4 (recipe fulfilment) -- NO, not by editing products_current_substitutions. That view
--      (and recipes_pos_resolved, which joins it) is SQLite-line, differential-tested by
--      .devtools/pgsql/view-tests/02_products_and_pricing.sql's "@views ...
--      products_current_substitutions" fixture -- its output is compared between engines for
--      shared fixture data. product_substitutions is PostgreSQL-only, so folding it into that
--      view would make the two engines' definitions diverge for a feature only one of them can
--      run, which is exactly what AGENTS.md's "do not delete SQLite behaviour the suite
--      compares against" is guarding. product_substitutions_resolved is therefore a wholly new
--      view, additive and untested by the differential harness, not a change to the existing
--      one; recipe fulfilment keeps using only the parent/child mechanism until a later plan
--      decides whether the response contract (ADR-0005) should carry the distinction.
--
-- SCHEMA. One table, edges keyed by the ordered pair, a self-edge refused by CHECK (the same
-- guard style as the SMALLINT flag CHECKs elsewhere in db/pgsql/baseline/01_tables.sql, not a
-- trigger, because there is no cross-row state to consult). No FOREIGN KEY to products,
-- matching every other product-referencing table in the baseline (product_barcodes,
-- quantity_unit_conversions, product_groups' own parent column) -- this schema does
-- application-level and trigger-level referential integrity, not FK-level.
CREATE TABLE product_substitutions (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	from_product_id INTEGER NOT NULL,
	to_product_id INTEGER NOT NULL,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	CONSTRAINT product_substitutions_no_self_edge CHECK (from_product_id != to_product_id),
	CONSTRAINT product_substitutions_pair_key UNIQUE (from_product_id, to_product_id)
);

-- CANDIDATES VIEW. "What on hand will do where this product is called for" -- the new
-- question the plan poses against products_current_substitutions' "what should be used
-- instead of this parent" -- has a different shape: several candidates per product, not one,
-- each with a reason. Both sources of substitutability are unioned here (the plan's own
-- instruction: "the view can union both") without disturbing the existing parent/child
-- mechanism, which stays exactly as products_current_substitutions and products_resolved
-- already define it. `direction` distinguishes a directed edge from the shared-parent case for
-- API/UI display.
--
-- Stock is read through products_resolved/stock_current, not stock_next_use, deliberately:
-- stock_next_use carries one row per physical stock entry, so joining it straight to
-- from_product_id would multiply a candidate row per stock entry the way
-- products_current_substitutions avoids only by ending in a single-row LIMIT 1. stock_current
-- is already the per-product rollup (keyed by the normalized top-level id
-- products_resolved.parent_product_id resolves to, exactly like a sub product's own stock
-- rolls up to its parent today), so it gives one candidate row per edge with an amount and a
-- best-before date to order by, and a candidate that is itself a sub product is normalized to
-- its own rollup the same way the existing mechanism already treats it.
CREATE VIEW product_substitutions_resolved AS

WITH edges(from_product_id, to_product_id, direction) AS (

	SELECT
		ps.from_product_id,
		ps.to_product_id,
		'directed' AS direction
	FROM product_substitutions ps

	UNION

	SELECT
		pr.sub_product_id AS from_product_id,
		pr.parent_product_id AS to_product_id,
		'shared_parent' AS direction
	FROM products_resolved pr
	WHERE pr.sub_product_id != pr.parent_product_id
)

SELECT
	1 AS id, -- Dummy, LessQL needs an id column
	e.to_product_id,
	e.from_product_id,
	e.direction,
	COALESCE(sc.amount, 0) AS from_product_amount_in_stock,
	sc.best_before_date AS from_product_best_before_date
FROM edges e
LEFT JOIN products_resolved pr_from
	ON pr_from.sub_product_id = e.from_product_id
LEFT JOIN stock_current sc
	ON sc.product_id = pr_from.parent_product_id;

-- CASCADE DELETE. product_substitutions joins trg_cascade_product_removal's existing list
-- (db/pgsql/baseline/06_triggers_a.sql) rather than getting a trigger of its own.
-- CREATE OR REPLACE FUNCTION keeps every existing DELETE unchanged (including the AFTER
-- trigger's own RETURN NULL) and adds the one this table needs, on both from_product_id and
-- to_product_id, since either side of an edge losing its product invalidates the row; the
-- trigger binding itself (`cascade_product_removal AFTER DELETE ON products`, unchanged) does
-- not need re-declaring because only the function body changes, unlike
-- migrations/0277.pgsql.sql's DROP/CREATE TRIGGER, which had to widen the event list itself.
CREATE OR REPLACE FUNCTION trg_cascade_product_removal() RETURNS TRIGGER AS $$
BEGIN
	DELETE FROM stock
	WHERE product_id = OLD.id;

	DELETE FROM stock_log
	WHERE product_id = OLD.id;

	DELETE FROM product_barcodes
	WHERE product_id = OLD.id;

	DELETE FROM quantity_unit_conversions
	WHERE product_id = OLD.id;

	DELETE FROM recipes_pos
	WHERE product_id = OLD.id;

	UPDATE recipes
	SET product_id = NULL
	WHERE product_id = OLD.id;

	DELETE FROM meal_plan
	WHERE product_id = OLD.id
		AND type = 'product';

	DELETE FROM shopping_list
	WHERE product_id = OLD.id;

	DELETE FROM userfield_values
	WHERE object_id = OLD.id::text
		AND field_id IN (SELECT id FROM userfields WHERE entity = 'products');

	DELETE FROM product_substitutions
	WHERE from_product_id = OLD.id
		OR to_product_id = OLD.id;

	RETURN NULL;
END;
$$ LANGUAGE plpgsql;
