-- ADR-0037 (issue #612): a retirement event for every stock-entry label retirement, so that an
-- undo of the whole-row consumption that retired a label can revive that label and no other.
--
-- WHAT THIS ADDS.
--   - stock_amounts_equal(): ADR-0032's amount tolerance in SQL, the same formula as
--     StockService::CompareAmounts(), for the trigger's amount check.
--   - stock_label_retirements: one row per retirement of a `stock_entry` label. It is history:
--     a row changes once, from pending to closed, and is never deleted (guard trigger below).
--     It has a foreign key to `labels` only. It has none to `stock`, `stock_log` or `products`,
--     which DatabaseImporter::Import() truncates with RESTART IDENTITY (ADR-0021 decision 3).
--   - record_stock_label_retirement(), an AFTER UPDATE OF retired_at trigger on `labels`, so
--     every retirement path writes its event, including direct SQL and later retirement sites.
--   - The legacy backfill: one closed `legacy` event for every stock-entry label retired before
--     this migration. It infers nothing, so a legacy label is never revivable.
--   - print_jobs (label_uid, id), for the trigger's jobs_through_id lookup and for the claim
--     predicate in PrintAttemptService::Claim().
--
-- WHAT PROVES A CONSUMPTION. StockService::ConsumeProduct() writes the whole-row booking and,
-- before it deletes the row, sets two transaction-local settings: the booking id
-- (victual.retiring_booking_id) and the revival window in seconds
-- (victual.label_revival_window_seconds). The trigger accepts that context only when the
-- booking exists, is live, is a `consume` or a negative `inventory-correction`, names the
-- deleted row in stock_row_id and has the snapshot's amount. Anything else - no context, an
-- older image, a console session, a stale value left by an earlier delete in the same
-- transaction, a forged value - records `unproven`, which no undo can claim.
--
-- WHAT IT DOES NOT CHANGE. No retire_* function, no column of `labels`, not its CHECK. Revival
-- itself is application code (StockLabelRevivalService), run inside the undo transaction.
--
-- Rerunnable in the sense ADR-0037 requires of the backfill: a second run of the backfill
-- statement writes nothing, because it skips labels that already have an event.

CREATE FUNCTION stock_amounts_equal(a DOUBLE PRECISION, b DOUBLE PRECISION) RETURNS BOOLEAN
LANGUAGE sql IMMUTABLE STRICT AS $$
	SELECT abs(a - b) <= GREATEST(1e-9, 1e-12 * GREATEST(abs(a), abs(b)))
$$;

CREATE TABLE stock_label_retirements (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	label_uid TEXT NOT NULL REFERENCES labels (uid),
	retired_at TIMESTAMPTZ NOT NULL,
	snapshot JSONB NOT NULL,
	cause TEXT NOT NULL CHECK (cause IN ('consumption', 'unproven', 'legacy')),
	import_epoch BIGINT,
	booking_id BIGINT,
	product_id BIGINT,
	amount DOUBLE PRECISION,
	jobs_through_id BIGINT,
	revivable_until TIMESTAMPTZ,
	outcome TEXT CHECK (outcome IN ('revived', 'declined')),
	reason TEXT CHECK (reason IN ('expired', 'label_live', 'mismatch', 'id_changed', 'target_labelled', 'unproven', 'legacy')),
	closed_at TIMESTAMPTZ,
	revived_target_id BIGINT,
	CONSTRAINT stock_label_retirements_booking_iff_consumption
		CHECK ((cause = 'consumption') = (booking_id IS NOT NULL)),
	CONSTRAINT stock_label_retirements_consumption_complete
		CHECK (cause <> 'consumption' OR (product_id IS NOT NULL AND amount IS NOT NULL AND import_epoch IS NOT NULL
			AND jobs_through_id IS NOT NULL AND revivable_until IS NOT NULL)),
	CONSTRAINT stock_label_retirements_epoch_unless_legacy
		CHECK (cause = 'legacy' OR import_epoch IS NOT NULL),
	CONSTRAINT stock_label_retirements_unprovable_closed
		CHECK (cause = 'consumption' OR COALESCE(outcome = 'declined' AND reason = cause, false)),
	CONSTRAINT stock_label_retirements_consumption_reason
		CHECK (cause <> 'consumption' OR reason IS NULL OR reason NOT IN ('unproven', 'legacy')),
	CONSTRAINT stock_label_retirements_closed_iff_outcome
		CHECK ((outcome IS NULL) = (closed_at IS NULL)),
	CONSTRAINT stock_label_retirements_revived_iff_target
		CHECK (COALESCE(outcome = 'revived', false) = (revived_target_id IS NOT NULL)),
	CONSTRAINT stock_label_retirements_declined_iff_reason
		CHECK (COALESCE(outcome = 'declined', false) = (reason IS NOT NULL))
);
CREATE UNIQUE INDEX stock_label_retirements_booking ON stock_label_retirements (import_epoch, booking_id)
	WHERE booking_id IS NOT NULL;
CREATE UNIQUE INDEX stock_label_retirements_one_pending ON stock_label_retirements (label_uid)
	WHERE outcome IS NULL;
CREATE INDEX stock_label_retirements_label ON stock_label_retirements (label_uid);
CREATE INDEX print_jobs_label_uid_id ON print_jobs (label_uid, id);

-- R4: an event changes once, from pending to closed, and only in its outcome columns. Nothing
-- deletes it. TRUNCATE is not guarded: the importer never names this table
-- (DatabaseImporter::NOT_COPIED_TABLES) and `labels`, the one table it references, is never
-- truncated either.
CREATE FUNCTION guard_stock_label_retirement_history() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
	IF TG_OP = 'DELETE' THEN
		RAISE EXCEPTION 'stock_label_retirements is history; event % cannot be deleted', OLD.id;
	END IF;
	IF OLD.outcome IS NOT NULL THEN
		RAISE EXCEPTION 'stock_label_retirements event % is already closed', OLD.id;
	END IF;
	IF NEW.outcome IS NULL
		OR (NEW.id, NEW.label_uid, NEW.retired_at, NEW.snapshot, NEW.cause, NEW.import_epoch, NEW.booking_id,
			NEW.product_id, NEW.amount, NEW.jobs_through_id, NEW.revivable_until)
		IS DISTINCT FROM (OLD.id, OLD.label_uid, OLD.retired_at, OLD.snapshot, OLD.cause, OLD.import_epoch, OLD.booking_id,
			OLD.product_id, OLD.amount, OLD.jobs_through_id, OLD.revivable_until) THEN
		RAISE EXCEPTION 'stock_label_retirements event % may only be closed, not otherwise changed', OLD.id;
	END IF;
	RETURN NEW;
END
$$;
CREATE TRIGGER guard_stock_label_retirement_history BEFORE UPDATE OR DELETE ON stock_label_retirements
FOR EACH ROW EXECUTE FUNCTION guard_stock_label_retirement_history();

CREATE FUNCTION record_stock_label_retirement() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	v_row BIGINT := (NEW.retirement_snapshot ->> 'id')::BIGINT;
	v_amount DOUBLE PRECISION := (NEW.retirement_snapshot ->> 'amount')::DOUBLE PRECISION;
	v_booking_text TEXT := current_setting('victual.retiring_booking_id', true);
	v_window_text TEXT := current_setting('victual.label_revival_window_seconds', true);
	v_booking BIGINT;
	v_window BIGINT;
	v_product BIGINT;
	v_booked DOUBLE PRECISION;
	v_through BIGINT;
BEGIN
	-- A malformed setting is treated exactly like a missing one: unproven, never an error that
	-- would abort the consumption it describes.
	IF v_booking_text ~ '^[0-9]{1,18}$' AND v_window_text ~ '^[0-9]{1,9}$' THEN
		v_booking := v_booking_text::BIGINT;
		v_window := v_window_text::BIGINT;
	END IF;

	IF v_booking IS NOT NULL AND v_window > 0 AND v_row IS NOT NULL AND v_amount IS NOT NULL THEN
		SELECT l.product_id, -l.amount INTO v_product, v_booked
		FROM stock_log l
		WHERE l.id = v_booking AND l.stock_row_id = v_row AND l.undone = 0 AND l.amount < 0
			AND l.transaction_type IN ('consume', 'inventory-correction');
		IF FOUND AND stock_amounts_equal(v_booked, v_amount) THEN
			SELECT COALESCE(MAX(j.id), 0) INTO v_through FROM print_jobs j WHERE j.label_uid = NEW.uid;
			INSERT INTO stock_label_retirements (label_uid, retired_at, snapshot, cause, import_epoch, booking_id,
				product_id, amount, jobs_through_id, revivable_until)
			VALUES (NEW.uid, NEW.retired_at, NEW.retirement_snapshot, 'consumption', label_current_import_epoch(), v_booking,
				v_product, v_booked, v_through, NEW.retired_at + make_interval(secs => v_window));
			RETURN NULL;
		END IF;
	END IF;

	INSERT INTO stock_label_retirements (label_uid, retired_at, snapshot, cause, import_epoch, outcome, reason, closed_at)
	VALUES (NEW.uid, NEW.retired_at, NEW.retirement_snapshot, 'unproven', label_current_import_epoch(), 'declined', 'unproven',
		NEW.retired_at);
	RETURN NULL;
END
$$;
CREATE TRIGGER record_stock_label_retirement AFTER UPDATE OF retired_at ON labels
FOR EACH ROW WHEN (OLD.retired_at IS NULL AND NEW.retired_at IS NOT NULL AND NEW.kind = 'stock_entry')
EXECUTE FUNCTION record_stock_label_retirement();

-- Legacy retirements: kept as history, closed at creation, never revivable. The snapshot's row
-- id can equal a booking's stock_row_id, but nothing proves the booking belongs to the same
-- database generation, so no booking, epoch or deadline is inferred. A function, so pgTAP can
-- show that a second run writes nothing.
CREATE FUNCTION backfill_legacy_stock_label_retirements() RETURNS BIGINT LANGUAGE sql AS $$
	WITH inserted AS (
		INSERT INTO stock_label_retirements (label_uid, retired_at, snapshot, cause, outcome, reason, closed_at)
		SELECT l.uid, l.retired_at, l.retirement_snapshot, 'legacy', 'declined', 'legacy', l.retired_at
		FROM labels l
		WHERE l.kind = 'stock_entry' AND l.retired_at IS NOT NULL
			AND NOT EXISTS (SELECT 1 FROM stock_label_retirements e WHERE e.label_uid = l.uid)
		RETURNING 1)
	SELECT count(*) FROM inserted
$$;

-- R1: the number of retired stock-entry labels without exactly one event. Zero after the
-- backfill; the migration fails otherwise.
CREATE FUNCTION stock_label_retirements_incomplete() RETURNS BIGINT LANGUAGE sql STABLE AS $$
	SELECT count(*)
	FROM labels l
	WHERE l.kind = 'stock_entry' AND l.retired_at IS NOT NULL
		AND (SELECT count(*) FROM stock_label_retirements e WHERE e.label_uid = l.uid) <> 1
$$;

-- Migrations run in a transaction, so a failure here rolls the whole migration back.
DO $$
DECLARE
	v_bad BIGINT;
BEGIN
	PERFORM backfill_legacy_stock_label_retirements();
	v_bad := stock_label_retirements_incomplete();
	IF v_bad > 0 THEN
		RAISE EXCEPTION 'ADR-0037 backfill left % retired stock-entry label(s) without exactly one event', v_bad;
	END IF;
END
$$;
