-- ADR-0036 (issue #665): a stock row's quantity is attributed to the bookings that added it.
--
-- WHAT THIS ADDS.
--   - stock_row_lots: the contributions. One row per (stock row, lot) holding the amount of
--     that lot the row holds now. lot_id NULL is the row's unattributed pool. Current state:
--     deleted with its stock row.
--   - stock_booking_lots: the allocations. One row per (booking, lot) holding the signed
--     amount of that lot the booking added, removed or moved. The record: kept as long as the
--     booking, immutable except for a unit-conversion rescale.
--   - stock_lineage_families(): the backfill's classification of legacy history into the
--     families E, X, U and N of ADR-0036's Migration section.
--   - stock_lineage_backfill(): writes `derived` and `unknown` contributions and allocations for
--     families that hold no lineage data yet, in one statement. Used by this migration, by the
--     application's lazy reclassification (StockLineage) and by the importer.
--   - stock_lineage_violations(): invariants I1 to I3, checked by this migration, by the
--     importer and by the tests.
--   - trg_cascade_change_qu_id_stock() redefined to rescale both new tables with `stock` and
--     `stock_log` (ADR-0036 section 3, unit conversion).
--
-- WHAT IT DOES NOT CHANGE. No column of `stock`, `stock_log`, `stock_entry_origins` or `labels`
-- and no row of them: the backfill reads them and writes only the two new tables. No view.
-- No wire contract: neither table is an exposed entity.
--
-- NO TEMPORARY TABLES. The application role cannot create them (deploy/postgres/roles.sql
-- revokes ALL on the database from PUBLIC), and the lazy path runs as that role, so the backfill
-- is one statement over CTEs instead of the spike's temporary tables.
--
-- CORRUPT INPUT. A non-finite amount (NaN or +/-Infinity, which `stock_amount_non_negative_check`
-- admits) in `stock` or `stock_log` cannot be attributed and makes the backfill raise, which
-- rolls this migration back. So does any I1, I2 or I3 violation left after the backfill.
--
-- RERUNNABLE. The backfill classifies only families with no contribution and no allocation, so
-- a second run writes nothing.

CREATE TABLE stock_row_lots (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	stock_row_id INTEGER NOT NULL REFERENCES stock (id) ON DELETE CASCADE,
	-- NULL: the row's unattributed pool, quantity whose lot is unknown.
	lot_id INTEGER REFERENCES stock_log (id) ON DELETE CASCADE,
	amount DOUBLE PRECISION NOT NULL CHECK (amount > 0 AND amount < 'Infinity'),
	basis TEXT NOT NULL CHECK (basis IN ('recorded', 'derived', 'unknown')),
	CONSTRAINT stock_row_lots_row_lot UNIQUE NULLS NOT DISTINCT (stock_row_id, lot_id),
	CONSTRAINT stock_row_lots_pool_iff_unknown CHECK ((lot_id IS NULL) = (basis = 'unknown'))
);
CREATE INDEX ix_stock_row_lots_lot ON stock_row_lots (lot_id);

CREATE TABLE stock_booking_lots (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	booking_id INTEGER NOT NULL REFERENCES stock_log (id) ON DELETE CASCADE,
	-- NULL: a recorded draw on (or return to) the unattributed pool.
	lot_id INTEGER REFERENCES stock_log (id) ON DELETE CASCADE,
	amount DOUBLE PRECISION NOT NULL CHECK (amount <> 0 AND amount > '-Infinity' AND amount < 'Infinity'),
	basis TEXT NOT NULL CHECK (basis IN ('recorded', 'derived', 'unknown')),
	CONSTRAINT stock_booking_lots_booking_lot UNIQUE NULLS NOT DISTINCT (booking_id, lot_id),
	-- An 'unknown' basis marks a lot whose units cannot be located; the pool itself is only
	-- ever drawn on by a recorded booking.
	CONSTRAINT stock_booking_lots_pool_recorded CHECK (lot_id IS NOT NULL OR basis = 'recorded')
);
CREATE INDEX ix_stock_booking_lots_lot ON stock_booking_lots (lot_id, booking_id);

-- An addition booking introduces a lot. stock-edit-new also does when it raises a row, but only
-- a lineage-aware writer knows that; legacy history treats it as a movement of the family's lot.
CREATE FUNCTION stock_log_is_addition(p_type TEXT, p_amount DOUBLE PRECISION) RETURNS BOOLEAN
LANGUAGE sql IMMUTABLE AS $$
	SELECT p_type IN ('purchase', 'self-production') OR (p_type = 'inventory-correction' AND p_amount > 0)
$$;

-- A booking's signed effect on its family's quantity, as invariant I3 counts it.
CREATE FUNCTION stock_log_lineage_delta(p_type TEXT, p_amount DOUBLE PRECISION) RETURNS DOUBLE PRECISION
LANGUAGE sql IMMUTABLE AS $$
	SELECT CASE p_type
		WHEN 'stock-edit-old' THEN -p_amount
		WHEN 'product-opened' THEN 0
		WHEN 'stock-measured-new' THEN 0
		WHEN 'stock-measured-old' THEN 0
		ELSE p_amount END
$$;

-- Families: a tag plus the tags stock_entry_origins links to it, per product. Only families
-- without any lineage data are returned, so the backfill never mixes `derived` rows into what a
-- lineage-aware writer recorded.
CREATE FUNCTION stock_lineage_families(p_product INTEGER DEFAULT NULL)
RETURNS TABLE (product_id INTEGER, stock_id TEXT, root TEXT, class TEXT)
LANGUAGE sql STABLE AS $$
	WITH ids AS (
		SELECT s.product_id, s.stock_id FROM stock s WHERE p_product IS NULL OR s.product_id = p_product
		UNION
		SELECT l.product_id, l.stock_id FROM stock_log l
		WHERE (p_product IS NULL OR l.product_id = p_product) AND l.stock_id IS NOT NULL
	), fam AS (
		SELECT i.product_id, i.stock_id, COALESCE(o.origin_stock_id, i.stock_id) AS root
		FROM ids i LEFT JOIN stock_entry_origins o ON o.stock_id = i.stock_id
	), tracked AS (
		SELECT DISTINCT f.product_id, f.root
		FROM fam f
		WHERE EXISTS (SELECT 1 FROM stock s JOIN stock_row_lots rl ON rl.stock_row_id = s.id
				WHERE s.product_id = f.product_id AND s.stock_id = f.stock_id)
			OR EXISTS (SELECT 1 FROM stock_log l JOIN stock_booking_lots bl ON bl.booking_id = l.id
				WHERE l.product_id = f.product_id AND l.stock_id = f.stock_id)
	), live AS (
		SELECT f.product_id, f.root, l.amount, stock_log_is_addition(l.transaction_type, l.amount) AS is_add,
			stock_log_lineage_delta(l.transaction_type, l.amount) AS delta
		FROM stock_log l JOIN fam f ON f.stock_id = l.stock_id AND f.product_id = l.product_id
		WHERE l.undone = 0
	), b AS (
		SELECT live.product_id, live.root,
			count(*) FILTER (WHERE is_add) AS n_add,
			COALESCE(sum(amount) FILTER (WHERE is_add), 0) AS sum_add,
			count(*) FILTER (WHERE NOT is_add) AS n_other,
			COALESCE(sum(delta), 0) AS delta_sum
		FROM live GROUP BY live.product_id, live.root
	), r AS (
		SELECT f.product_id, f.root, count(s.id) AS n_rows, COALESCE(sum(s.amount), 0) AS rows_sum
		FROM fam f LEFT JOIN stock s ON s.stock_id = f.stock_id AND s.product_id = f.product_id
		GROUP BY f.product_id, f.root
	), stat AS (
		SELECT r.product_id, r.root,
			CASE
				WHEN COALESCE(b.n_add, 0) = 0 AND r.n_rows = 0 THEN 'N'
				WHEN COALESCE(b.n_add, 0) = 1 AND stock_amounts_equal(COALESCE(b.delta_sum, 0), r.rows_sum) THEN 'E'
				WHEN COALESCE(b.n_add, 0) >= 2 AND COALESCE(b.n_other, 0) = 0 AND r.n_rows = 1
					AND stock_amounts_equal(b.sum_add, r.rows_sum) THEN 'X'
				ELSE 'U' END AS class
		FROM r LEFT JOIN b ON b.product_id = r.product_id AND b.root = r.root
	)
	SELECT f.product_id, f.stock_id, f.root, st.class
	FROM fam f
	JOIN stat st ON st.product_id = f.product_id AND st.root = f.root
	WHERE NOT EXISTS (SELECT 1 FROM tracked t WHERE t.product_id = f.product_id AND t.root = f.root)
$$;

-- The backfill. One statement, so every part reads the same snapshot of which families are
-- untracked. Writes nothing to stock, stock_log, stock_entry_origins or labels.
--   E: every row of the family is a contribution of the one live addition; every booking of the
--      family, live or undone, is allocated to it (an addition to itself).
--   X: the one row holds each live addition's amount; only the additions are allocated.
--   U: each row becomes one pool contribution; each live addition gets an `unknown`
--      self-allocation; other bookings stay untracked.
--   N: nothing.
CREATE FUNCTION stock_lineage_backfill(p_product INTEGER DEFAULT NULL)
RETURNS TABLE (family_class TEXT, families BIGINT, stock_rows BIGINT)
LANGUAGE plpgsql AS $$
DECLARE
	v_bad TEXT;
BEGIN
	SELECT 'stock row ' || s.id INTO v_bad FROM stock s
	WHERE (p_product IS NULL OR s.product_id = p_product) AND s.amount IN ('NaN', 'Infinity', '-Infinity') LIMIT 1;
	IF v_bad IS NULL THEN
		SELECT 'booking ' || l.id INTO v_bad FROM stock_log l
		WHERE (p_product IS NULL OR l.product_id = p_product) AND l.amount IN ('NaN', 'Infinity', '-Infinity') LIMIT 1;
	END IF;
	IF v_bad IS NOT NULL THEN
		RAISE EXCEPTION 'ADR-0036 backfill: % has a non-finite amount and cannot be attributed', v_bad;
	END IF;

	RETURN QUERY
	WITH fam AS MATERIALIZED (
		SELECT * FROM stock_lineage_families(p_product)
	), lots AS MATERIALIZED (
		SELECT DISTINCT f.product_id, f.root, f.class, l.id AS lot_id, l.amount AS lot_amount
		FROM fam f JOIN stock_log l ON l.stock_id = f.stock_id AND l.product_id = f.product_id
		WHERE f.class IN ('E', 'X') AND l.undone = 0 AND stock_log_is_addition(l.transaction_type, l.amount)
	), ins_rows AS (
		INSERT INTO stock_row_lots (stock_row_id, lot_id, amount, basis)
		SELECT s.id, lo.lot_id, CASE WHEN f.class = 'E' THEN s.amount ELSE lo.lot_amount END, 'derived'
		FROM stock s
		JOIN fam f ON f.stock_id = s.stock_id AND f.product_id = s.product_id
		JOIN lots lo ON lo.product_id = f.product_id AND lo.root = f.root
		WHERE s.amount > 0
		RETURNING 1
	), ins_pool AS (
		INSERT INTO stock_row_lots (stock_row_id, lot_id, amount, basis)
		SELECT s.id, NULL, s.amount, 'unknown'
		FROM stock s JOIN fam f ON f.stock_id = s.stock_id AND f.product_id = s.product_id
		WHERE f.class = 'U' AND s.amount > 0
		RETURNING 1
	), ins_bookings AS (
		INSERT INTO stock_booking_lots (booking_id, lot_id, amount, basis)
		SELECT l.id,
			CASE WHEN stock_log_is_addition(l.transaction_type, l.amount) THEN l.id
				ELSE (SELECT lo.lot_id FROM lots lo WHERE lo.product_id = f.product_id AND lo.root = f.root) END,
			l.amount,
			CASE WHEN f.class IN ('E', 'X') THEN 'derived' ELSE 'unknown' END
		FROM stock_log l JOIN fam f ON f.stock_id = l.stock_id AND f.product_id = l.product_id
		WHERE l.amount <> 0 AND f.class <> 'N'
			AND (f.class = 'E' OR stock_log_is_addition(l.transaction_type, l.amount))
		RETURNING 1
	), counts AS (
		SELECT (SELECT count(*) FROM ins_rows) + (SELECT count(*) FROM ins_pool) + (SELECT count(*) FROM ins_bookings) AS n
	)
	SELECT f.class, count(DISTINCT (f.product_id, f.root)),
		(SELECT count(*) FROM stock s JOIN fam g ON g.stock_id = s.stock_id AND g.product_id = s.product_id WHERE g.class = f.class)
	FROM fam f CROSS JOIN counts
	GROUP BY f.class, counts.n;
END
$$;

-- Invariants I1 to I3 of ADR-0036 section 3, for one product or all. Empty when they hold.
--   I1: a row with amount > 0 holds contributions summing to its amount.
--   I2: a booking with allocations has allocations summing to its amount.
--   I3: a lot with a `recorded` or `derived` allocation has live allocations (counted as
--       stock_log_lineage_delta() counts bookings) summing to its contributions.
CREATE FUNCTION stock_lineage_violations(p_product INTEGER DEFAULT NULL)
RETURNS TABLE (invariant TEXT, subject_id INTEGER, expected DOUBLE PRECISION, actual DOUBLE PRECISION)
LANGUAGE sql STABLE AS $$
	SELECT 'I1', s.id, s.amount, COALESCE(sum(rl.amount), 0)
	FROM stock s LEFT JOIN stock_row_lots rl ON rl.stock_row_id = s.id
	WHERE (p_product IS NULL OR s.product_id = p_product)
	GROUP BY s.id, s.amount
	HAVING (s.amount > 0 OR count(rl.id) > 0) AND NOT COALESCE(stock_amounts_equal(s.amount, COALESCE(sum(rl.amount), 0)), false)
	UNION ALL
	SELECT 'I2', l.id, l.amount, sum(bl.amount)
	FROM stock_log l JOIN stock_booking_lots bl ON bl.booking_id = l.id
	WHERE p_product IS NULL OR l.product_id = p_product
	GROUP BY l.id, l.amount
	HAVING NOT COALESCE(stock_amounts_equal(l.amount, sum(bl.amount)), false)
	UNION ALL
	SELECT 'I3', n.lot_id, n.net, COALESCE(h.held, 0)
	FROM (
		SELECT bl.lot_id, sum(stock_log_lineage_delta(l.transaction_type, bl.amount)) AS net
		FROM stock_booking_lots bl JOIN stock_log l ON l.id = bl.booking_id
		JOIN stock_log lot ON lot.id = bl.lot_id
		WHERE l.undone = 0 AND bl.basis <> 'unknown' AND (p_product IS NULL OR lot.product_id = p_product)
			AND NOT EXISTS (SELECT 1 FROM stock_booking_lots u WHERE u.lot_id = bl.lot_id AND u.basis = 'unknown')
		GROUP BY bl.lot_id
	) n
	LEFT JOIN (
		SELECT rl.lot_id, sum(rl.amount) AS held FROM stock_row_lots rl WHERE rl.lot_id IS NOT NULL GROUP BY rl.lot_id
	) h ON h.lot_id = n.lot_id
	WHERE NOT COALESCE(stock_amounts_equal(n.net, COALESCE(h.held, 0)), false)
$$;


-- trg_cascade_change_qu_id_stock, as 0294 left it, plus the rescale of both new tables. The
-- trigger declaration (db/pgsql/baseline/06_triggers_a.sql) is unchanged.
CREATE OR REPLACE FUNCTION trg_cascade_change_qu_id_stock() RETURNS TRIGGER AS $$
DECLARE
	v_factor DOUBLE PRECISION;
BEGIN
	-- All amounts anywhere are related to the products stock QU,
	-- so apply the appropriate unit conversion to all amounts everywhere on change
	-- (and enforce that such a conversion need to exist when the product was once added to stock)

	-- (the "AND NEW.qu_id_stock != OLD.qu_id_stock" from the original stock_log subquery is
	-- dropped here - it is guaranteed true already by this trigger's WHEN clause)
	IF NOT EXISTS(
			SELECT 1
			FROM quantity_unit_conversions_resolved
			WHERE product_id = NEW.id
				AND from_qu_id = OLD.qu_id_stock
				AND to_qu_id = NEW.qu_id_stock
		)
		AND EXISTS(
			SELECT 1
			FROM stock_log
			WHERE product_id = NEW.id
		)
	THEN
		RAISE EXCEPTION 'qu_id_stock can only be changed when a corresponding QU conversion (old QU => new QU) exists when the product was once added to stock';
	END IF;

	v_factor := COALESCE((SELECT factor FROM quantity_unit_conversions_resolved WHERE product_id = NEW.id AND from_qu_id = OLD.qu_id_stock AND to_qu_id = NEW.qu_id_stock LIMIT 1), 1.0);

	-- Issue #546: refuse before touching anything, mirroring MergeProducts()'s own guard
	-- (services/StockService.php) against the same stock_measurement_coherence_check. A
	-- factor of 1 leaves every amount unchanged and can never violate it, so only a genuine
	-- rescale is refused. `stock` only, not `stock_log` - see this file's header comment
	-- for why checking the ledger here would lock the product's unit permanently.
	IF v_factor != 1.0
		AND EXISTS(SELECT 1 FROM stock WHERE product_id = NEW.id AND opened_amount IS NOT NULL)
	THEN
		RAISE EXCEPTION 'qu_id_stock cannot be changed by a non-1 conversion factor while this product has a measured open container';
	END IF;

	UPDATE chores
	SET product_amount = product_amount * v_factor
	WHERE product_id = NEW.id;

	UPDATE meal_plan
	SET product_amount = product_amount * v_factor
	WHERE type = 'product'
		AND product_id = NEW.id;

	UPDATE recipes_pos
	SET amount = amount * v_factor
	WHERE product_id = NEW.id;

	UPDATE shopping_list
	SET amount = amount * v_factor
	WHERE product_id = NEW.id
		AND product_id IS NOT NULL;

	UPDATE stock
	SET amount = amount * v_factor,
		price = price / v_factor
	WHERE product_id = NEW.id;

	UPDATE stock_log
	SET amount = amount * v_factor,
		price = price / v_factor
	WHERE product_id = NEW.id;

	-- ADR-0036 section 3: contributions and allocations are amounts in the stock unit too, and
	-- I1 to I3 compare them with stock.amount and stock_log.amount, so they rescale by the same
	-- factor in the same transaction.
	UPDATE stock_row_lots rl
	SET amount = rl.amount * v_factor
	FROM stock s
	WHERE s.id = rl.stock_row_id
		AND s.product_id = NEW.id;

	UPDATE stock_booking_lots bl
	SET amount = bl.amount * v_factor
	FROM stock_log l
	WHERE l.id = bl.booking_id
		AND l.product_id = NEW.id;

	-- Issue #543: product_location_min_stock.min_stock_amount (migrations/0276.pgsql.sql)
	-- is stored in the product's stock unit exactly like the amounts above, and belongs in
	-- the same transaction as the rest of this rescale. A different table than the row
	-- this trigger is mid-UPDATE on, so it needs its own UPDATE (unlike products.min_stock_amount
	-- just below).
	UPDATE product_location_min_stock
	SET min_stock_amount = min_stock_amount * v_factor
	WHERE product_id = NEW.id;

	-- Issue #543: products.min_stock_amount is the same class of miss - stored in the
	-- product's own stock unit, never rescaled. This is the row already being updated, so
	-- it is set directly on NEW rather than through a second UPDATE, exactly the way
	-- trg_cascade_change_qu_id_stock2 (migrations/0275.pgsql.sql) already rescales
	-- quick_consume_amount and quick_open_amount on this same row.
	NEW.min_stock_amount := NEW.min_stock_amount * v_factor;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Backfill and validate. Migrations run in a transaction, so a raise here rolls this whole
-- migration back, tables included.
DO $$
DECLARE
	v_violation RECORD;
BEGIN
	PERFORM stock_lineage_backfill(NULL);
	SELECT * INTO v_violation FROM stock_lineage_violations(NULL) LIMIT 1;
	IF FOUND THEN
		RAISE EXCEPTION 'ADR-0036 backfill left invariant % violated for % % (expected %, found %)',
			v_violation.invariant,
			CASE v_violation.invariant WHEN 'I1' THEN 'stock row' WHEN 'I2' THEN 'booking' ELSE 'lot' END,
			v_violation.subject_id, v_violation.expected, v_violation.actual;
	END IF;
END
$$;
