-- ADR-0040 and ADR-0041 (plan 22, issue #698): private consumption recipes, their shares and the
-- consumption events that record a recipe being consumed.
--
-- WHAT THIS ADDS.
--   - consumption_recipes: an owned list of product lines a person consumes together, such as a
--     prescription. Separate from the food `recipes` table; a food recipe is global and has no
--     owner. Deleted with its owner (ADR-0040 rule 5).
--   - consumption_recipe_lines: the household-entered product quantities, each in the unit the
--     person entered. The stock quantity is derived at consumption through the product's own
--     quantity unit conversions; nothing here converts or infers a conversion.
--   - consumption_recipe_shares: the rights a named user holds on one recipe. `read` is implied
--     by any row. A share confers no permission (ADR-0040 rule 2): the global permission an act
--     needs is checked separately, at use time. A share never names the recipe's owner.
--   - consumption_events: one row per recorded consumption, identified by (user, source_system,
--     source_event_id) (ADR-0041 rule 1). `manual` events are created by consuming a recipe in
--     Victual. External-source columns and the mapping table arrive with issue #700.
--   - consumption_event_lines: what an event booked, as booked: product, stock-unit amount and
--     source location, so a later recipe edit never changes what a past event consumed.
--   - trg_consumption_share_not_owner() and trg_consumption_owner_not_sharee(): database
--     enforcement of "a share never names the owner".
--
-- WHAT IT DOES NOT CHANGE. No existing table, column, view or function. No permission row: ADR-0040
-- adds no permission constant and no permission_hierarchy row. `stock_log.recipe_id` is never set
-- for a consumption recipe; the link from bookings to a recipe is consumption_events.transaction_id.
-- None of these tables is an exposed entity (EntityReadPolicy and the ExposedEntity enum omit
-- them on purpose), so every generic route answers 400 for them.
--
-- RERUNNABLE. Every statement is guarded with IF NOT EXISTS or CREATE OR REPLACE, so a second
-- run changes nothing.

CREATE TABLE IF NOT EXISTS consumption_recipes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owner_user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	name TEXT NOT NULL,
	note TEXT,
	row_created_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
	row_updated_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT consumption_recipes_name_not_blank CHECK (length(btrim(name)) > 0)
);

CREATE INDEX IF NOT EXISTS ix_consumption_recipes_owner_user_id ON consumption_recipes (owner_user_id);

-- A deleted product removes its lines, as trg_cascade_product_removal() already removes
-- recipes_pos rows: a RESTRICT here would tell whoever deletes a product that some private
-- recipe uses it. A deleted quantity unit or location is refused, as it is for products.
CREATE TABLE IF NOT EXISTS consumption_recipe_lines (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recipe_id INTEGER NOT NULL REFERENCES consumption_recipes (id) ON DELETE CASCADE,
	position INTEGER NOT NULL,
	product_id INTEGER NOT NULL REFERENCES products (id) ON DELETE CASCADE,
	amount DOUBLE PRECISION NOT NULL,
	qu_id INTEGER NOT NULL REFERENCES quantity_units (id),
	CONSTRAINT consumption_recipe_lines_amount_positive CHECK (amount > 0 AND amount < 'Infinity'),
	CONSTRAINT consumption_recipe_lines_position_positive CHECK (position > 0),
	CONSTRAINT consumption_recipe_lines_recipe_position_key UNIQUE (recipe_id, position)
);

CREATE INDEX IF NOT EXISTS ix_consumption_recipe_lines_product_id ON consumption_recipe_lines (product_id);

CREATE TABLE IF NOT EXISTS consumption_recipe_shares (
	recipe_id INTEGER NOT NULL REFERENCES consumption_recipes (id) ON DELETE CASCADE,
	user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	can_consume SMALLINT NOT NULL DEFAULT 0 CHECK (can_consume IN (0, 1)),
	can_edit SMALLINT NOT NULL DEFAULT 0 CHECK (can_edit IN (0, 1)),
	can_undo SMALLINT NOT NULL DEFAULT 0 CHECK (can_undo IN (0, 1)),
	can_share SMALLINT NOT NULL DEFAULT 0 CHECK (can_share IN (0, 1)),
	granted_by_user_id INTEGER REFERENCES users (id) ON DELETE SET NULL,
	granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY (recipe_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_consumption_recipe_shares_user_id ON consumption_recipe_shares (user_id);

CREATE OR REPLACE FUNCTION trg_consumption_share_not_owner() RETURNS TRIGGER AS $$
BEGIN
	IF EXISTS (SELECT 1 FROM consumption_recipes WHERE id = NEW.recipe_id AND owner_user_id = NEW.user_id) THEN
		RAISE EXCEPTION 'A share cannot name the owner of the consumption recipe'
			USING ERRCODE = '23514';
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS consumption_share_not_owner ON consumption_recipe_shares;
CREATE TRIGGER consumption_share_not_owner BEFORE INSERT OR UPDATE OF recipe_id, user_id ON consumption_recipe_shares
FOR EACH ROW EXECUTE FUNCTION trg_consumption_share_not_owner();

CREATE OR REPLACE FUNCTION trg_consumption_owner_not_sharee() RETURNS TRIGGER AS $$
BEGIN
	IF EXISTS (SELECT 1 FROM consumption_recipe_shares WHERE recipe_id = NEW.id AND user_id = NEW.owner_user_id) THEN
		RAISE EXCEPTION 'The new owner of a consumption recipe must not hold a share on it'
			USING ERRCODE = '23514';
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS consumption_owner_not_sharee ON consumption_recipes;
CREATE TRIGGER consumption_owner_not_sharee BEFORE UPDATE OF owner_user_id ON consumption_recipes
FOR EACH ROW EXECUTE FUNCTION trg_consumption_owner_not_sharee();

-- ADR-0041 rule 2. An event outlives its recipe: deleting the recipe clears recipe_id and keeps the
-- event, its transaction_id and its lines, so stock history is unchanged.
CREATE TABLE IF NOT EXISTS consumption_events (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	source_system TEXT NOT NULL,
	source_event_id TEXT NOT NULL,
	recipe_id INTEGER REFERENCES consumption_recipes (id) ON DELETE SET NULL,
	state TEXT NOT NULL,
	reason TEXT,
	transaction_id TEXT,
	revision INTEGER NOT NULL DEFAULT 1,
	payload_hash TEXT,
	occurred_at TIMESTAMPTZ NOT NULL,
	received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT consumption_events_identity_key UNIQUE (user_id, source_system, source_event_id),
	CONSTRAINT consumption_events_source_system_form CHECK (source_system ~ '^[a-z0-9][a-z0-9._-]{0,31}$'),
	CONSTRAINT consumption_events_source_event_id_form CHECK (source_event_id ~ '^[A-Za-z0-9._:-]{1,128}$'),
	CONSTRAINT consumption_events_state_known CHECK (state IN
		('received', 'needs_mapping', 'needs_review', 'booked', 'undone', 'voided', 'linked', 'dismissed')),
	CONSTRAINT consumption_events_reason_known CHECK (reason IS NULL OR reason IN
		('ambiguous_location', 'insufficient_stock', 'unit_unconfirmed', 'quantity_missing', 'recipe_unavailable',
		 'partially_undone', 'changed_after_undo', 'undo_refused', 'invalid_mapping', 'source_deleted', 'stock_error')),
	CONSTRAINT consumption_events_reason_only_in_review CHECK ((reason IS NULL) = (state <> 'needs_review')),
	CONSTRAINT consumption_events_booked_has_transaction CHECK (state <> 'booked' OR transaction_id IS NOT NULL),
	CONSTRAINT consumption_events_revision_positive CHECK (revision > 0)
);

CREATE INDEX IF NOT EXISTS ix_consumption_events_user_state ON consumption_events (user_id, state);
CREATE INDEX IF NOT EXISTS ix_consumption_events_recipe_id ON consumption_events (recipe_id);
-- A stock transaction belongs to at most one event (ADR-0041 rule 9): a correction or a rebook gives
-- the same event a new transaction id, a void keeps its id, and a link is refused when the
-- transaction is already attached.
CREATE UNIQUE INDEX IF NOT EXISTS ux_consumption_events_transaction_id ON consumption_events (transaction_id)
	WHERE transaction_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS consumption_event_lines (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_id INTEGER NOT NULL REFERENCES consumption_events (id) ON DELETE CASCADE,
	product_id INTEGER NOT NULL REFERENCES products (id) ON DELETE CASCADE,
	amount DOUBLE PRECISION NOT NULL,
	location_id INTEGER REFERENCES locations (id),
	stock_log_id INTEGER REFERENCES stock_log (id) ON DELETE SET NULL,
	CONSTRAINT consumption_event_lines_amount_positive CHECK (amount > 0 AND amount < 'Infinity')
);

CREATE INDEX IF NOT EXISTS ix_consumption_event_lines_event_id ON consumption_event_lines (event_id);
CREATE INDEX IF NOT EXISTS ix_consumption_event_lines_stock_log_id ON consumption_event_lines (stock_log_id);
