-- ADR-0041 (plan 22, issue #700): the source mapping table, and the columns that let the existing
-- consumption_events and consumption_event_lines tables (migration 0305) record an event reported
-- by an external client. There is no second ledger: an external event is a row of the same table a
-- `manual` event uses, with the same identity (user, source_system, source_event_id).
--
-- WHAT THIS ADDS.
--   - consumption_mappings: what a person has approved for one (source_system, medication_ref): a
--     target (one consumption recipe, or one product with an optional unit and quantity factor), the
--     unit labels the person has confirmed, an optional default quantity, a location rule and the
--     instant before which events are dismissed (ADR-0041 rule 4). Owned by one user and never
--     read by another. `manual` is reserved and cannot be a mapping's source_system.
--   - consumption_events: the request fields the event was booked from (so a correction can be
--     compared and a retry can book without the client), the client's `source_updated_at`, the
--     mapping used, the local `occurred_date`, the audit-only API key, the event it replaces, `voided_at`, the source's removal
--     record, the candidate locations of an ambiguous source, the private stock refusal message, and
--     `linked_transaction_id` for an explicit link to an existing booking (ADR-0041 rule 9).
--   - consumption_event_lines: `used_date`, the calendar date each line was booked under.
--
-- WHAT IT DOES NOT CHANGE. No state or reason is added or removed: 0305's lists already hold every
-- ADR-0041 state and reason. No existing row changes meaning (every new column is nullable or
-- defaulted). No permission row. The new table is not an exposed entity: EntityReadPolicy and the
-- ExposedEntity enum omit it on purpose, so every generic route answers 400 for it (ADR-0040 rule 1).
-- Nothing here is added to stock_log, and no existing view or function is touched.
--
-- ON TOMBSTONES (ADR-0041 open question 2). A `voided` or `dismissed` event is kept while its mapping
-- exists. Deleting a mapping is done by the service, in one transaction, and removes that mapping's
-- tombstones with it; events that booked stock survive, with mapping_id cleared, because the stock
-- ledger keeps the transaction either way.
--
-- RERUNNABLE. Every statement is guarded with IF NOT EXISTS, so a second run changes nothing.

CREATE TABLE IF NOT EXISTS consumption_mappings (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	source_system TEXT NOT NULL,
	medication_ref TEXT NOT NULL,
	target_type TEXT NOT NULL,
	-- A deleted recipe leaves the mapping in place with no target: an event then needs review
	-- (recipe_unavailable) instead of silently booking nothing or disappearing.
	recipe_id INTEGER REFERENCES consumption_recipes (id) ON DELETE SET NULL,
	product_id INTEGER REFERENCES products (id) ON DELETE CASCADE,
	-- The unit the event quantity is expressed in. NULL means the product's stock unit.
	qu_id INTEGER REFERENCES quantity_units (id),
	quantity_factor DOUBLE PRECISION NOT NULL DEFAULT 1,
	unit_labels TEXT[] NOT NULL DEFAULT '{}',
	default_quantity DOUBLE PRECISION,
	location_mode TEXT NOT NULL,
	location_id INTEGER REFERENCES locations (id),
	effective_from TIMESTAMPTZ NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT consumption_mappings_identity_key UNIQUE (user_id, source_system, medication_ref),
	CONSTRAINT consumption_mappings_source_system_form CHECK (source_system ~ '^[a-z0-9][a-z0-9._-]{0,31}$'),
	CONSTRAINT consumption_mappings_manual_reserved CHECK (source_system <> 'manual'),
	CONSTRAINT consumption_mappings_medication_ref_form CHECK (medication_ref ~ '^[A-Za-z0-9._:-]{1,128}$'),
	CONSTRAINT consumption_mappings_target_known CHECK (target_type IN ('recipe', 'product')),
	CONSTRAINT consumption_mappings_target_shape CHECK (
		(target_type = 'recipe' AND product_id IS NULL AND qu_id IS NULL)
		OR (target_type = 'product' AND product_id IS NOT NULL AND recipe_id IS NULL)),
	CONSTRAINT consumption_mappings_factor_positive CHECK (quantity_factor > 0 AND quantity_factor < 'Infinity'),
	CONSTRAINT consumption_mappings_default_quantity_positive CHECK (default_quantity IS NULL OR (default_quantity > 0 AND default_quantity < 'Infinity')),
	CONSTRAINT consumption_mappings_unit_labels_clean CHECK (array_position(unit_labels, '') IS NULL
		AND array_position(unit_labels, NULL) IS NULL AND cardinality(unit_labels) <= 50),
	CONSTRAINT consumption_mappings_location_mode_known CHECK (location_mode IN ('fixed', 'single', 'explicit')),
	CONSTRAINT consumption_mappings_fixed_names_location CHECK ((location_mode = 'fixed') = (location_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS ix_consumption_mappings_recipe_id ON consumption_mappings (recipe_id);
CREATE INDEX IF NOT EXISTS ix_consumption_mappings_product_id ON consumption_mappings (product_id);

-- Request fields as submitted, from which a correction is compared and a retry books. The payload
-- hash (0305) covers status, medication_ref, quantity, unit_label, occurred_at and location_id.
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS mapping_id INTEGER REFERENCES consumption_mappings (id) ON DELETE SET NULL;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS medication_ref TEXT;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS submitted_status TEXT;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS quantity DOUBLE PRECISION;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS unit_label TEXT;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS requested_location_id INTEGER REFERENCES locations (id) ON DELETE SET NULL;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS source_updated_at TIMESTAMPTZ;
-- The calendar date of occurred_at in the offset the client sent, which is the date a booking is made
-- under (ADR-0041 rule 5). Kept because the instant alone no longer says which local date it was, and
-- a retry or resolve books long after the request that carried the offset.
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS occurred_date DATE;
-- Audit only (ADR-0041 rule 1): identity is never scoped to the key.
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS api_key_id INTEGER REFERENCES api_keys (id) ON DELETE SET NULL;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS replaces_event_id INTEGER REFERENCES consumption_events (id) ON DELETE SET NULL;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS source_removed_at TIMESTAMPTZ;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS source_removed_reason TEXT;
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS candidate_location_ids INTEGER[];
-- Private to the event's user: the refusal text of a stock error the service could not classify.
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS stock_error_message TEXT;
-- An explicit link to an existing booking transaction (ADR-0041 rule 9). The event's own
-- transaction_id stays NULL or is undone when a booked event is linked, so exactly one deduction
-- remains. The unique index below holds the transaction to one link.
ALTER TABLE consumption_events ADD COLUMN IF NOT EXISTS linked_transaction_id TEXT;

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'consumption_events_submitted_status_known') THEN
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_submitted_status_known CHECK (submitted_status IS NULL
			OR submitted_status IN ('taken', 'not_logged', 'skipped', 'unanswered', 'scheduled'));
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_medication_ref_form CHECK (medication_ref IS NULL
			OR medication_ref ~ '^[A-Za-z0-9._:-]{1,128}$');
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_quantity_positive CHECK (quantity IS NULL
			OR (quantity > 0 AND quantity < 'Infinity'));
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_removed_pair CHECK ((source_removed_at IS NULL) = (source_removed_reason IS NULL));
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_removed_reason_known CHECK (source_removed_reason IS NULL
			OR source_removed_reason IN ('entered_in_error', 'history_cleared', 'medication_archived', 'access_revoked', 'unknown'));
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_voided_has_time CHECK (state <> 'voided' OR voided_at IS NOT NULL);
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_linked_pair CHECK ((state = 'linked') = (linked_transaction_id IS NOT NULL));
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_not_self_replacing CHECK (replaces_event_id IS NULL OR replaces_event_id <> id);
		-- `manual` is the server's own source: it has no mapping, medication or source-supplied fields.
		ALTER TABLE consumption_events ADD CONSTRAINT consumption_events_manual_has_no_source_fields CHECK (source_system <> 'manual'
			OR (mapping_id IS NULL AND medication_ref IS NULL AND submitted_status IS NULL AND source_updated_at IS NULL
				AND replaces_event_id IS NULL AND api_key_id IS NULL));
	END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_consumption_events_linked_transaction_id ON consumption_events (linked_transaction_id)
	WHERE linked_transaction_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_consumption_events_mapping_id ON consumption_events (mapping_id);
CREATE INDEX IF NOT EXISTS ix_consumption_events_replaces_event_id ON consumption_events (replaces_event_id);
-- The bulk-resolution filter and the inbox: one user's events for a medication, oldest occurred_at first.
CREATE INDEX IF NOT EXISTS ix_consumption_events_user_medication ON consumption_events (user_id, source_system, medication_ref, state, occurred_at, id);
-- possible_duplicates: a user's manual events near a time.
CREATE INDEX IF NOT EXISTS ix_consumption_events_user_occurred_at ON consumption_events (user_id, occurred_at);

ALTER TABLE consumption_event_lines ADD COLUMN IF NOT EXISTS used_date DATE;
