-- ADR-0042 (plan 22, issue #701): refill history, reorder rules and notice acknowledgements for a
-- private consumption recipe (a prescription). Every row belongs to one consumption_recipes row and
-- is private under ADR-0040: a reader needs the `read` right, a writer the `edit` right, and the
-- tables are reachable through the dedicated routes only.
--
-- WHAT THIS ADDS.
--   - consumption_refill_settings: at most one row per recipe. The medication-specific reorder rule
--     (days_before_end, fixed_interval or fraction_elapsed, each with one integer parameter) and the
--     recipe's warning-lead override. A recipe without a row uses the fallback rule and the default
--     lead. A fraction is an integer percent, never a floating-point number (ADR-0042 rule 2).
--   - consumption_refill_fills: the fill history. A fill is never edited and never deleted by the
--     application: a wrong fill is voided with a reason and a new one is recorded. `filled_on` is
--     the calendar date the pharmacy supplied the medication and `supplied_days` the days of supply
--     that fill was entered with. Both are what the person entered; the server never supplies them.
--   - consumption_refill_dates: an explicit reorder date a person entered for one fill. It ends,
--     permanently, when a newer fill is recorded or when its own fill is voided, so a stale date is
--     never carried forward and voiding the newer fill does not bring it back (ADR-0042 rule 2).
--     At most one live (un-ended) date exists per recipe.
--   - consumption_refill_orders: a request to the pharmacy. It adds no stock and records no fill.
--     At most one open order exists per recipe. Receiving an order closes it against the fill that
--     arrived, in one transaction.
--   - consumption_refill_acks: which notice a user has acknowledged. The recipe, kind and reorder
--     date are columns, not only a key, so ADR-0040 access applies to the row. The notice key
--     `<recipe_id>:<kind>:<reorder_date>` is built from them.
--   - Six trigger functions that hold the invariants no CHECK can express: the fill history is
--     immutable apart from a void, a newer fill (or a void) ends the explicit date it supersedes, an
--     explicit date is not earlier than its fill, and a closed order stays closed.
--
-- DATES. Every `_on`, `reorder_date` and `warning` value is a SQL DATE and travels as YYYY-MM-DD
-- (ADR-0027, ADR-0042 rule 4). Nothing here uses CURRENT_DATE, now() as a date, or a date default:
-- "today" is supplied by the request, so no stored or derived date depends on the session zone. The
-- instants (`created_at`, `voided_at`, `ended_at`, `closed_at`, `acknowledged_at`) are TIMESTAMPTZ.
--
-- WHAT IT DOES NOT CHANGE. No existing table, column, view or function. No permission row, no role
-- and no share right (ADR-0042 rule 1). None of these tables is an exposed entity, so EntityReadPolicy
-- and the ExposedEntity enum omit them on purpose and every generic route answers 400 (ADR-0040
-- rule 1). Nothing here writes stock_log, and nothing in the stock ledger reads these tables.
--
-- DELETION. All five tables reference the recipe with ON DELETE CASCADE, matching ADR-0040 rule 5:
-- deleting a recipe or its owner removes its refill history with it. An acknowledgement also goes
-- with its user. The immutability trigger on fills does not fire on a delete, so that cascade works.
--
-- RERUNNABLE. Every statement is guarded with IF NOT EXISTS or CREATE OR REPLACE, so a second run
-- changes nothing.

CREATE TABLE IF NOT EXISTS consumption_refill_settings (
	recipe_id INTEGER PRIMARY KEY REFERENCES consumption_recipes (id) ON DELETE CASCADE,
	rule_kind TEXT,
	rule_parameter INTEGER,
	warning_lead_days INTEGER,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT consumption_refill_settings_rule_kind_known CHECK (rule_kind IS NULL
		OR rule_kind IN ('days_before_end', 'fixed_interval', 'fraction_elapsed')),
	CONSTRAINT consumption_refill_settings_rule_pair CHECK ((rule_kind IS NULL) = (rule_parameter IS NULL)),
	-- N from 0 to 730, D from 1 to 730, P (an integer percent) from 1 to 99.
	CONSTRAINT consumption_refill_settings_rule_parameter_range CHECK (rule_kind IS NULL
		OR (rule_kind = 'days_before_end' AND rule_parameter BETWEEN 0 AND 730)
		OR (rule_kind = 'fixed_interval' AND rule_parameter BETWEEN 1 AND 730)
		OR (rule_kind = 'fraction_elapsed' AND rule_parameter BETWEEN 1 AND 99)),
	CONSTRAINT consumption_refill_settings_warning_lead_range CHECK (warning_lead_days IS NULL
		OR warning_lead_days BETWEEN 0 AND 60)
);

CREATE TABLE IF NOT EXISTS consumption_refill_fills (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recipe_id INTEGER NOT NULL REFERENCES consumption_recipes (id) ON DELETE CASCADE,
	filled_on DATE NOT NULL,
	-- Optional: a fixed_interval rule and an explicit date do not use it. A fallback or a
	-- days_before_end or fraction_elapsed estimate without it is `unknown` / `invalid_supply`.
	supplied_days INTEGER,
	note TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	voided_at TIMESTAMPTZ,
	void_reason TEXT,
	-- Lets a dependent row name a fill and its recipe together, so it cannot point at another
	-- recipe's fill.
	CONSTRAINT consumption_refill_fills_id_recipe_key UNIQUE (id, recipe_id),
	CONSTRAINT consumption_refill_fills_supplied_days_range CHECK (supplied_days IS NULL OR supplied_days BETWEEN 1 AND 730),
	CONSTRAINT consumption_refill_fills_note_length CHECK (note IS NULL OR (length(btrim(note)) > 0 AND length(note) <= 2000)),
	CONSTRAINT consumption_refill_fills_void_pair CHECK ((voided_at IS NULL) = (void_reason IS NULL)),
	CONSTRAINT consumption_refill_fills_void_reason_not_blank CHECK (void_reason IS NULL OR length(btrim(void_reason)) > 0)
);

-- The current fill is the unvoided fill with the greatest filled_on, then the greatest id.
CREATE INDEX IF NOT EXISTS ix_consumption_refill_fills_current ON consumption_refill_fills (recipe_id, filled_on DESC, id DESC)
	WHERE voided_at IS NULL;

CREATE TABLE IF NOT EXISTS consumption_refill_dates (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recipe_id INTEGER NOT NULL REFERENCES consumption_recipes (id) ON DELETE CASCADE,
	fill_id INTEGER NOT NULL,
	reorder_on DATE NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	ended_at TIMESTAMPTZ,
	ended_reason TEXT,
	CONSTRAINT consumption_refill_dates_fill_fkey FOREIGN KEY (fill_id, recipe_id)
		REFERENCES consumption_refill_fills (id, recipe_id) ON DELETE CASCADE,
	CONSTRAINT consumption_refill_dates_end_pair CHECK ((ended_at IS NULL) = (ended_reason IS NULL)),
	CONSTRAINT consumption_refill_dates_ended_reason_known CHECK (ended_reason IS NULL
		OR ended_reason IN ('superseded', 'fill_voided', 'replaced', 'cleared'))
);

-- At most one live explicit date per recipe (ADR-0042 section 1).
CREATE UNIQUE INDEX IF NOT EXISTS ux_consumption_refill_dates_live ON consumption_refill_dates (recipe_id)
	WHERE ended_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_consumption_refill_dates_fill_id ON consumption_refill_dates (fill_id);

CREATE TABLE IF NOT EXISTS consumption_refill_orders (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recipe_id INTEGER NOT NULL REFERENCES consumption_recipes (id) ON DELETE CASCADE,
	ordered_on DATE NOT NULL,
	state TEXT NOT NULL DEFAULT 'open',
	received_fill_id INTEGER,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	closed_at TIMESTAMPTZ,
	CONSTRAINT consumption_refill_orders_received_fill_fkey FOREIGN KEY (received_fill_id, recipe_id)
		REFERENCES consumption_refill_fills (id, recipe_id),
	CONSTRAINT consumption_refill_orders_state_known CHECK (state IN ('open', 'received', 'cancelled')),
	CONSTRAINT consumption_refill_orders_closed_pair CHECK ((state = 'open') = (closed_at IS NULL)),
	CONSTRAINT consumption_refill_orders_received_has_fill CHECK ((state = 'received') = (received_fill_id IS NOT NULL))
);

-- At most one open order per recipe (ADR-0042 section 7). A second concurrent order is a conflict.
CREATE UNIQUE INDEX IF NOT EXISTS ux_consumption_refill_orders_open ON consumption_refill_orders (recipe_id)
	WHERE state = 'open';
CREATE INDEX IF NOT EXISTS ix_consumption_refill_orders_recipe_id ON consumption_refill_orders (recipe_id, ordered_on DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_consumption_refill_orders_received_fill_id ON consumption_refill_orders (received_fill_id)
	WHERE received_fill_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS consumption_refill_acks (
	user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	recipe_id INTEGER NOT NULL REFERENCES consumption_recipes (id) ON DELETE CASCADE,
	kind TEXT NOT NULL,
	reorder_date DATE NOT NULL,
	acknowledged_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	PRIMARY KEY (user_id, recipe_id, kind, reorder_date),
	CONSTRAINT consumption_refill_acks_kind_known CHECK (kind IN ('approaching', 'due'))
);

CREATE INDEX IF NOT EXISTS ix_consumption_refill_acks_recipe_id ON consumption_refill_acks (recipe_id);

-- A fill is history. Only a void changes it, once: the entered facts stay as they were entered, and
-- a voided fill is never revived (ADR-0042 section 5: correct by voiding and recording again).
CREATE OR REPLACE FUNCTION trg_consumption_refill_fill_immutable() RETURNS TRIGGER AS $$
BEGIN
	IF NEW.recipe_id IS DISTINCT FROM OLD.recipe_id
		OR NEW.filled_on IS DISTINCT FROM OLD.filled_on
		OR NEW.supplied_days IS DISTINCT FROM OLD.supplied_days
		OR NEW.note IS DISTINCT FROM OLD.note
		OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
		RAISE EXCEPTION 'A refill fill is history and cannot be edited; void it and record a new one'
			USING ERRCODE = '23514';
	END IF;

	IF OLD.voided_at IS NOT NULL AND (NEW.voided_at IS DISTINCT FROM OLD.voided_at OR NEW.void_reason IS DISTINCT FROM OLD.void_reason) THEN
		RAISE EXCEPTION 'A voided refill fill cannot be changed or revived'
			USING ERRCODE = '23514';
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS consumption_refill_fill_immutable ON consumption_refill_fills;
CREATE TRIGGER consumption_refill_fill_immutable BEFORE UPDATE ON consumption_refill_fills
FOR EACH ROW EXECUTE FUNCTION trg_consumption_refill_fill_immutable();

-- A newer fill permanently ends the explicit date entered for an older one. "Newer" is the order
-- that decides the current fill: filled_on, then id. A fill recorded with an earlier date than the
-- fill an explicit date belongs to is not newer, and leaves that date alone.
CREATE OR REPLACE FUNCTION trg_consumption_refill_fill_supersedes_dates() RETURNS TRIGGER AS $$
BEGIN
	UPDATE consumption_refill_dates d
	SET ended_at = now(), ended_reason = 'superseded'
	FROM consumption_refill_fills older
	WHERE d.recipe_id = NEW.recipe_id
		AND d.ended_at IS NULL
		AND older.id = d.fill_id
		AND (older.filled_on, older.id) < (NEW.filled_on, NEW.id);
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS consumption_refill_fill_supersedes_dates ON consumption_refill_fills;
CREATE TRIGGER consumption_refill_fill_supersedes_dates AFTER INSERT ON consumption_refill_fills
FOR EACH ROW EXECUTE FUNCTION trg_consumption_refill_fill_supersedes_dates();

-- Voiding a fill ends the explicit date entered for it. An older fill's date was already ended by
-- the newer fill, so voiding the newer fill revives nothing.
CREATE OR REPLACE FUNCTION trg_consumption_refill_void_ends_dates() RETURNS TRIGGER AS $$
BEGIN
	UPDATE consumption_refill_dates
	SET ended_at = now(), ended_reason = 'fill_voided'
	WHERE fill_id = NEW.id AND ended_at IS NULL;
	RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS consumption_refill_void_ends_dates ON consumption_refill_fills;
CREATE TRIGGER consumption_refill_void_ends_dates AFTER UPDATE OF voided_at ON consumption_refill_fills
FOR EACH ROW WHEN (OLD.voided_at IS NULL AND NEW.voided_at IS NOT NULL)
EXECUTE FUNCTION trg_consumption_refill_void_ends_dates();

-- An explicit date is not earlier than the fill it belongs to, and belongs to an unvoided fill.
-- The service refuses with 422 first; this is the backstop for any other writer.
CREATE OR REPLACE FUNCTION trg_consumption_refill_date_not_before_fill() RETURNS TRIGGER AS $$
DECLARE
	fill_date DATE;
	fill_voided TIMESTAMPTZ;
BEGIN
	SELECT filled_on, voided_at INTO fill_date, fill_voided FROM consumption_refill_fills WHERE id = NEW.fill_id;

	IF NEW.reorder_on < fill_date THEN
		RAISE EXCEPTION 'An explicit reorder date cannot be earlier than the fill it was entered for'
			USING ERRCODE = '23514';
	END IF;

	IF NEW.ended_at IS NULL AND fill_voided IS NOT NULL THEN
		RAISE EXCEPTION 'An explicit reorder date cannot be live on a voided fill'
			USING ERRCODE = '23514';
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS consumption_refill_date_not_before_fill ON consumption_refill_dates;
CREATE TRIGGER consumption_refill_date_not_before_fill BEFORE INSERT ON consumption_refill_dates
FOR EACH ROW EXECUTE FUNCTION trg_consumption_refill_date_not_before_fill();

-- An explicit date is entered once: it can be ended, and nothing else about it changes.
CREATE OR REPLACE FUNCTION trg_consumption_refill_date_ends_once() RETURNS TRIGGER AS $$
BEGIN
	IF NEW.recipe_id IS DISTINCT FROM OLD.recipe_id
		OR NEW.fill_id IS DISTINCT FROM OLD.fill_id
		OR NEW.reorder_on IS DISTINCT FROM OLD.reorder_on
		OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
		RAISE EXCEPTION 'An explicit reorder date cannot be edited; end it and enter a new one'
			USING ERRCODE = '23514';
	END IF;

	IF OLD.ended_at IS NOT NULL AND (NEW.ended_at IS DISTINCT FROM OLD.ended_at OR NEW.ended_reason IS DISTINCT FROM OLD.ended_reason) THEN
		RAISE EXCEPTION 'An ended explicit reorder date cannot be revived or changed'
			USING ERRCODE = '23514';
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS consumption_refill_date_ends_once ON consumption_refill_dates;
CREATE TRIGGER consumption_refill_date_ends_once BEFORE UPDATE ON consumption_refill_dates
FOR EACH ROW EXECUTE FUNCTION trg_consumption_refill_date_ends_once();

-- A closed order stays closed (ADR-0042 section 5): received and cancelled are final, and the dates
-- and the recipe an order was recorded with do not change.
CREATE OR REPLACE FUNCTION trg_consumption_refill_order_closed_final() RETURNS TRIGGER AS $$
BEGIN
	IF NEW.recipe_id IS DISTINCT FROM OLD.recipe_id
		OR NEW.ordered_on IS DISTINCT FROM OLD.ordered_on
		OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
		RAISE EXCEPTION 'A refill order cannot be edited; cancel it and record a new one'
			USING ERRCODE = '23514';
	END IF;

	IF OLD.state <> 'open' AND (NEW.state IS DISTINCT FROM OLD.state
		OR NEW.received_fill_id IS DISTINCT FROM OLD.received_fill_id
		OR NEW.closed_at IS DISTINCT FROM OLD.closed_at) THEN
		RAISE EXCEPTION 'A closed refill order cannot be reopened or changed'
			USING ERRCODE = '23514';
	END IF;

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS consumption_refill_order_closed_final ON consumption_refill_orders;
CREATE TRIGGER consumption_refill_order_closed_final BEFORE UPDATE ON consumption_refill_orders
FOR EACH ROW EXECUTE FUNCTION trg_consumption_refill_order_closed_final();
