-- ADR-0021 prerequisite 3: the import refusal, under concurrency.
--
-- Shaped after services/Database/DatabaseImporter.php as it stands: AssertTargetIsEmpty()
-- runs BEFORE beginTransaction(), the truncate is TRUNCATE ... RESTART IDENTITY CASCADE
-- inside one transaction, and ResyncGeneratedIdCounters() runs after the commit. The
-- question is where a label guard has to sit to be safe, and the answer is demonstrated
-- rather than asserted.
DROP SCHEMA IF EXISTS adr21 CASCADE;
CREATE SCHEMA adr21;
SET search_path TO adr21;

CREATE TABLE locations (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

-- No foreign key to locations, deliberately. An FK would put every label and every
-- retirement snapshot in TRUNCATE ... CASCADE's path and erase exactly the history the
-- retirement design promises. target_id is nulled on retirement so a retired row can never
-- be reached by a live (kind, target_id) lookup after an id is reused.
CREATE TABLE labels (
    uid           text PRIMARY KEY,
    kind          text NOT NULL,
    target_id     bigint,
    snapshot_name text,
    retired_at    timestamptz
);

CREATE UNIQUE INDEX labels_one_live_per_target
    ON labels (kind, target_id) WHERE retired_at IS NULL;

-- The one lock both paths take. 0x1abe1 is arbitrary; what matters is that issuance and
-- import name the same number, so neither can run inside the other's window.
CREATE OR REPLACE FUNCTION label_lock() RETURNS void LANGUAGE sql AS
$$ SELECT pg_advisory_xact_lock(109038) $$;

-- Issuance: one transaction, the lock, then mint.
CREATE OR REPLACE FUNCTION issue_label(p_uid text, p_target bigint) RETURNS text
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM label_lock();
    IF NOT EXISTS (SELECT 1 FROM locations WHERE id = p_target) THEN
        RETURN 'refused: no such location';
    END IF;
    INSERT INTO labels (uid, kind, target_id) VALUES (p_uid, 'location', p_target);
    RETURN 'issued';
END $$;

-- The import, in two shapes. `p_guard_inside` chooses whether the live-label count is
-- taken inside the transaction under the lock, or before it the way AssertTargetIsEmpty
-- does today.
CREATE OR REPLACE FUNCTION import_body(p_guard_inside boolean, p_rows text[])
RETURNS text LANGUAGE plpgsql AS $$
DECLARE live_labels integer;
BEGIN
    IF p_guard_inside THEN
        PERFORM label_lock();
        SELECT count(*) INTO live_labels FROM labels WHERE retired_at IS NULL;
        IF live_labels > 0 THEN
            RAISE EXCEPTION 'import refused: % live label(s) name rows this import replaces',
                live_labels USING ERRCODE = 'raise_exception';
        END IF;
    END IF;
    TRUNCATE TABLE locations RESTART IDENTITY CASCADE;
    INSERT INTO locations (id, name) SELECT i, p_rows[i] FROM generate_subscripts(p_rows, 1) AS i;
    PERFORM setval(pg_get_serial_sequence('adr21.locations', 'id'),
                   (SELECT coalesce(max(id), 1) FROM locations));
    RETURN 'imported ' || array_length(p_rows, 1) || ' location(s)';
END $$;

-- What an authorized caller sees when a uid is scanned.
CREATE OR REPLACE FUNCTION resolve(p_uid text) RETURNS text LANGUAGE plpgsql AS $$
DECLARE l labels%ROWTYPE; n text;
BEGIN
    SELECT * INTO l FROM labels WHERE uid = p_uid;
    IF NOT FOUND THEN RETURN 'unknown'; END IF;
    IF l.retired_at IS NOT NULL THEN RETURN 'retired: ' || coalesce(l.snapshot_name, '?'); END IF;
    SELECT name INTO n FROM locations WHERE id = l.target_id;
    RETURN 'resolved: ' || coalesce(n, '<<DANGLING>>');
END $$;

CREATE OR REPLACE FUNCTION retire(p_uid text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
    UPDATE labels SET snapshot_name = (SELECT name FROM locations WHERE id = labels.target_id),
                      target_id = NULL, retired_at = now()
     WHERE uid = p_uid;
END $$;

-- Case 2b leaves a residue the lock alone does not remove: an issuance request composed
-- before an import and executed after it mints a label for whatever now holds that id.
-- The row is self-consistent -- the label names its current occupant -- but it is not what
-- the person asked for, and nothing tells them. A monotonic import epoch is enough to say
-- so: the caller reads it when it renders the print action, presents it when it asks, and
-- issuance refuses if the ground moved underneath.
CREATE TABLE import_epoch (epoch bigint NOT NULL);
INSERT INTO import_epoch VALUES (1);

CREATE OR REPLACE FUNCTION import_body(p_guard_inside boolean, p_rows text[])
RETURNS text LANGUAGE plpgsql AS $$
DECLARE live_labels integer;
BEGIN
    IF p_guard_inside THEN
        PERFORM label_lock();
        SELECT count(*) INTO live_labels FROM labels WHERE retired_at IS NULL;
        IF live_labels > 0 THEN
            RAISE EXCEPTION 'import refused: % live label(s) name rows this import replaces',
                live_labels USING ERRCODE = 'raise_exception';
        END IF;
    END IF;
    TRUNCATE TABLE locations RESTART IDENTITY CASCADE;
    INSERT INTO locations (id, name) SELECT i, p_rows[i] FROM generate_subscripts(p_rows, 1) AS i;
    PERFORM setval(pg_get_serial_sequence('adr21.locations', 'id'),
                   (SELECT coalesce(max(id), 1) FROM locations));
    UPDATE import_epoch SET epoch = epoch + 1;
    RETURN 'imported ' || array_length(p_rows, 1) || ' location(s)';
END $$;

CREATE OR REPLACE FUNCTION issue_label_at_epoch(p_uid text, p_target bigint, p_epoch bigint)
RETURNS text LANGUAGE plpgsql AS $$
DECLARE now_epoch bigint;
BEGIN
    PERFORM label_lock();
    SELECT epoch INTO now_epoch FROM import_epoch;
    IF now_epoch <> p_epoch THEN
        RETURN 'refused: the location set was replaced (epoch ' || p_epoch || ' -> ' || now_epoch || ')';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM locations WHERE id = p_target) THEN
        RETURN 'refused: no such location';
    END IF;
    INSERT INTO labels (uid, kind, target_id) VALUES (p_uid, 'location', p_target);
    RETURN 'issued';
END $$;
