<?php

namespace Victual\Controllers\Api;

use Victual\Controllers\Users\User;
use Victual\Controllers\Users\EntityReadPolicy;
use Victual\Services\FieldPolicy;
use Victual\Services\StockService;
use Victual\Services\UserfieldsService;
use Victual\Services\UsersService;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;

/**
 * Serves the generic CRUD endpoints /api/objects/{entity}[/{objectId}] and the
 * Userfields endpoints /api/userfields/{entity}/{objectId} for all entities
 * exposed through the OpenAPI spec (ExposedEntity* enums also control which
 * entities can be listed, edited, deleted or require admin rights).
 */
class GenericEntityApiController extends BaseApiController
{
	/**
	 * POST /api/objects/{entity} - creates a new object from the JSON request body.
	 * Requires an entity-dependent permission (shopping list, recipes, meal plan,
	 * equipment or MASTER_DATA_EDIT as fallback; some entities additionally ADMIN),
	 * answered with 403 when missing. As a side effect, creating a product may add
	 * below-min-stock products to the shopping list (per user setting).
	 * The columns the server owns (id, row_created_timestamp) are dropped from the body
	 * before it is written - see WithoutServerOwnedColumns().
	 * Returns { "created_object_id": int|string } (200) or a 400 error response
	 * (unknown/not exposed/not editable entity, invalid body, or a body that sets no
	 * column at all and would therefore create nothing).
	 */
	public function AddObject(Request $request, Response $response, array $args)
	{
		if ($args['entity'] == 'shopping_list' || $args['entity'] == 'shopping_lists')
		{
			User::CheckPermission($request, User::PERMISSION_SHOPPINGLIST_ITEMS_ADD);
		}
		elseif ($args['entity'] == 'recipes' || $args['entity'] == 'recipes_pos' || $args['entity'] == 'recipes_nestings')
		{
			User::CheckPermission($request, User::PERMISSION_RECIPES);
		}
		elseif ($args['entity'] == 'meal_plan')
		{
			User::CheckPermission($request, User::PERMISSION_RECIPES_MEALPLAN);
		}
		elseif ($args['entity'] == 'equipment')
		{
			User::CheckPermission($request, User::PERMISSION_EQUIPMENT);
		}
		else
		{
			User::CheckPermission($request, User::PERMISSION_MASTER_DATA_EDIT);
		}

		if ($this->IsValidExposedEntity($args['entity']) && !$this->IsEntityWithNoEdit($args['entity']))
		{
			if ($this->IsEntityWithEditRequiresAdmin($args['entity']))
			{
				User::CheckPermission($request, User::PERMISSION_ADMIN);
			}

			$requestBody = $this->GetParsedAndFilteredRequestBody($request, $args['entity']);

			return $this->HandleApiCall($response, function () use ($args, $requestBody, $response)
			{
				if ($requestBody === null)
				{
					throw new \Exception('Request body could not be parsed (probably invalid JSON format or missing/wrong Content-Type header)');
				}

				$requestBody = self::WithoutServerOwnedColumns($requestBody);

				if ($args['entity'] === 'locations')
				{
					$requestBody = $this->WithDerivedIsFreezer($requestBody);
				}
				elseif ($args['entity'] === 'products')
				{
					// A new product is never already tare-enabled, so any truthy value here
					// is an enable. See RefuseTareEnable().
					$this->RefuseTareEnable($requestBody, false);
				}

				if (empty($requestBody))
				{
					// LessQL skips the insert for a row with no modified columns, so the
					// endpoint used to ask the driver for the id of an insert that never
					// happened and answer 200 with whatever it said - "0" on SQLite, null
					// on PostgreSQL, an object id on neither. See issue #47.
					throw new EInvalidApiQuery('The request body sets no column of this entity, so there is nothing to create');
				}

				$newRow = $this->DB->{$args['entity']}()->createRow($requestBody);
				$newRow->save();

				// The id off the saved row, not $this->DB->lastInsertId().
				//
				// lastInsertId() with no sequence name is SELECT lastval() on PostgreSQL,
				// which returns the last value generated by *any* sequence in this
				// session - including one an AFTER INSERT trigger touched. products has
				// such a trigger: it writes to cache__quantity_unit_conversions_resolved,
				// whose own identity column then owns lastval(). So creating a product
				// answered with the cache table's id rather than the product's, and the
				// two only agree on a virgin database where the sequences happen to move
				// in step. Measured on PostgreSQL 16.13: a product actually created as
				// id 5 was reported as created_object_id "3", and a client that then
				// asked for product 3 got somebody else's product or a 404.
				//
				// LessQL's Row::save() already asks the right question - it looks the id
				// up as lastInsertId($db->getSequence($table)) and leaves it on the row -
				// so the value is there to be read. SQLite is unaffected either way, and
				// the "nothing was inserted" case is unchanged: save() skips a row with
				// no modified columns, the primary is never set, and this stays null (the
				// difference from upstream that issue #47 records).
				$newObjectId = $newRow->id;

				// TODO: This should be better done somehow in StockService
				if ($args['entity'] == 'products' && boolval(UsersService::GetInstance()->GetUserSetting(VICTUAL_USER_ID, 'shopping_list_auto_add_below_min_stock_amount')))
				{
					StockService::GetInstance()->AddMissingProductsToShoppingList(UsersService::GetInstance()->GetUserSetting(VICTUAL_USER_ID, 'shopping_list_auto_add_below_min_stock_amount_list_id'));
				}

				return $this->ApiResponse($response, [
					'created_object_id' => $newObjectId
				]);
			});
		}
		else
		{
			return $this->GenericErrorResponse($response, 'Entity does not exist or is not exposed');
		}
	}

	/**
	 * DELETE /api/objects/{entity}/{objectId} - deletes the given object.
	 * Requires an entity-dependent permission (as in AddObject), answered with 403
	 * when missing; api_keys need no such permission, but non-admins can only delete
	 * their own keys.
	 * Returns 204 on success, 404 when the object does not exist, or a 400 error
	 * response for an invalid/undeletable entity or a location that still has child
	 * locations.
	 */
	public function DeleteObject(Request $request, Response $response, array $args)
	{
		if ($args['entity'] == 'shopping_list' || $args['entity'] == 'shopping_lists')
		{
			User::CheckPermission($request, User::PERMISSION_SHOPPINGLIST_ITEMS_DELETE);
		}
		elseif ($args['entity'] == 'recipes' || $args['entity'] == 'recipes_pos' || $args['entity'] == 'recipes_nestings')
		{
			User::CheckPermission($request, User::PERMISSION_RECIPES);
		}
		elseif ($args['entity'] == 'meal_plan')
		{
			User::CheckPermission($request, User::PERMISSION_RECIPES_MEALPLAN);
		}
		elseif ($args['entity'] == 'equipment')
		{
			User::CheckPermission($request, User::PERMISSION_EQUIPMENT);
		}
		elseif ($args['entity'] == 'api_keys')
		{
			// No permission needed, ownership is checked below
		}
		else
		{
			User::CheckPermission($request, User::PERMISSION_MASTER_DATA_EDIT);
		}

		if ($this->IsValidExposedEntity($args['entity']) && !$this->IsEntityWithNoDelete($args['entity']))
		{
			if ($this->IsEntityWithEditRequiresAdmin($args['entity']))
			{
				User::CheckPermission($request, User::PERMISSION_ADMIN);
			}

			$row = $this->DB->{$args['entity']}($args['objectId']);
			if ($row == null)
			{
				return $this->GenericErrorResponse($response, 'Object not found', 404);
			}

			// API keys can only be deleted by their owner (or by any admin), otherwise
			// anybody could delete anybody's keys, as the ids are sequential.
			// Keys of other users are answered with the same "not found" response as
			// non-existing ones, so that this can't be used to enumerate valid ids.
			if ($args['entity'] == 'api_keys' && $row->user_id != VICTUAL_USER_ID)
			{
				if (!User::HasPermissions(User::PERMISSION_ADMIN))
				{
					return $this->GenericErrorResponse($response, 'Object not found', 404);
				}
			}

			// A location that has children is refused, per plan 08 question 2: reparenting
			// silently rewrites where things were and cascading deletes the location stock
			// rows point at. The database refuses it too - migrations/0273.pgsql.sql's
			// `guard_location_children` covers every other write path - but a trigger's text
			// can never reach a client, because GenericErrorResponse() replaces any message
			// beginning `SQLSTATE[` before rendering it. So the message a person reads has to
			// be raised here, and the two are worded identically on purpose.
			if ($args['entity'] == 'locations' && $this->DB->locations()->where('parent_location_id', $row->id)->fetch() != null)
			{
				return $this->GenericErrorResponse($response, 'Location has child locations', 400);
			}

			// Same reasoning as the location check above, for the same kind of tree: plan 30
			// blocks deleting a group with children rather than reparenting or cascading, and
			// migrations/0278.pgsql.sql's `guard_product_group_children` is the backstop for
			// every write path that does not come through here.
			if ($args['entity'] == 'product_groups' && $this->DB->product_groups()->where('parent_product_group_id', $row->id)->fetch() != null)
			{
				return $this->GenericErrorResponse($response, 'Product group has child groups', 400);
			}

			$row->delete();

			return $this->EmptyApiResponse($response);
		}
		else
		{
			return $this->GenericErrorResponse($response, 'Invalid entity');
		}
	}

	/**
	 * PUT /api/objects/{entity}/{objectId} - updates the given object with the JSON
	 * request body. Requires an entity-dependent permission (as in AddObject),
	 * answered with 403 when missing. As a side effect, editing a product may add
	 * below-min-stock products to the shopping list (per user setting).
	 * The columns the server owns (id, row_created_timestamp) are dropped from the body
	 * before it is written - see WithoutServerOwnedColumns().
	 * Returns 204 on success, 404 when the object does not exist, or a 400 error
	 * response (invalid/not editable entity or invalid body).
	 */
	public function EditObject(Request $request, Response $response, array $args)
	{
		if ($args['entity'] == 'shopping_list' || $args['entity'] == 'shopping_lists')
		{
			User::CheckPermission($request, User::PERMISSION_SHOPPINGLIST_ITEMS_ADD);
		}
		elseif ($args['entity'] == 'recipes' || $args['entity'] == 'recipes_pos' || $args['entity'] == 'recipes_nestings')
		{
			User::CheckPermission($request, User::PERMISSION_RECIPES);
		}
		elseif ($args['entity'] == 'meal_plan')
		{
			User::CheckPermission($request, User::PERMISSION_RECIPES_MEALPLAN);
		}
		elseif ($args['entity'] == 'equipment')
		{
			User::CheckPermission($request, User::PERMISSION_EQUIPMENT);
		}
		else
		{
			User::CheckPermission($request, User::PERMISSION_MASTER_DATA_EDIT);
		}

		if ($this->IsValidExposedEntity($args['entity']) && !$this->IsEntityWithNoEdit($args['entity']))
		{
			if ($this->IsEntityWithEditRequiresAdmin($args['entity']))
			{
				User::CheckPermission($request, User::PERMISSION_ADMIN);
			}

			$requestBody = $this->GetParsedAndFilteredRequestBody($request, $args['entity']);

			return $this->HandleApiCall($response, function () use ($args, $requestBody, $response)
			{
				if ($requestBody === null)
				{
					throw new \Exception('Request body could not be parsed (probably invalid JSON format or missing/wrong Content-Type header)');
				}

				$row = $this->DB->{$args['entity']}($args['objectId']);
				if ($row == null)
				{
					throw new EObjectNotFound('Object not found');
				}

				$requestBody = self::WithoutServerOwnedColumns($requestBody);

				if ($args['entity'] === 'locations')
				{
					$requestBody = $this->WithDerivedIsFreezer($requestBody);
				}
				elseif ($args['entity'] === 'products')
				{
					$this->RefuseTareEnable($requestBody, boolval($row->enable_tare_weight_handling));
				}

				$row->update($requestBody);

				// TODO: This should be better done somehow in StockService
				if ($args['entity'] == 'products' && boolval(UsersService::GetInstance()->GetUserSetting(VICTUAL_USER_ID, 'shopping_list_auto_add_below_min_stock_amount')))
				{
					StockService::GetInstance()->AddMissingProductsToShoppingList(UsersService::GetInstance()->GetUserSetting(VICTUAL_USER_ID, 'shopping_list_auto_add_below_min_stock_amount_list_id'));
				}

				return $this->EmptyApiResponse($response);
			});
		}
		else
		{
			return $this->GenericErrorResponse($response, 'Entity does not exist or is not exposed');
		}
	}

	/**
	 * GET /api/objects/{entity}/{objectId} - returns a single object including its
	 * Userfield values under the "userfields" key (null when none exist).
	 * Returns 400 for an unknown/not listable entity and 404 when the object does not exist.
	 */
	public function GetObject(Request $request, Response $response, array $args)
	{
		if (!EntityReadPolicy::Covers($args['entity']) || !$this->IsValidExposedEntity($args['entity']) || $this->IsEntityWithNoListing($args['entity']))
		{
			return $this->GenericErrorResponse($response, 'Entity does not exist or is not exposed');
		}
		EntityReadPolicy::Check($request, $args['entity']);
		$this->AssertWholeObjectReadable($request, $args['entity']);

		$object = $args['entity'] === 'label_printer_status'
			? $this->DB->label_printer_status()->where('printer_id', $args['objectId'])->fetch()
			: $this->DB->{$args['entity']}($args['objectId']);
		if ($args['entity'] === 'locations')
		{
			$object = $this->DB->locations()->select('id, name, description, row_created_timestamp, is_freezer, active, parent_location_id, storage_class_id, tare_weight, tare_qu_id')->where('id', $args['objectId'])->fetch();
		}
		if ($object == null)
		{
			return $this->GenericErrorResponse($response, 'Object not found', 404);
		}

		// TODO: Handle this somehow more generically
		$referencingId = $args['objectId'];
		if ($args['entity'] == 'stock')
		{
			$referencingId = $object->stock_id;
		}
		$userfields = UserfieldsService::GetInstance()->GetValues($args['entity'], $referencingId);
		if (count($userfields) === 0)
		{
			$userfields = null;
		}
		$object['userfields'] = $userfields;

		$object = FieldPolicy::GetInstance()->RedactRow($args['entity'], $object);

		return $this->ApiResponse($response, $object);
	}

	/**
	 * GET /api/objects/{entity} - lists all objects of the given entity, filterable via
	 * the generic query/limit/offset/order query parameters; when Userfields exist for
	 * the entity, each object gets a "userfields" key/value map attached.
	 * Returns 400 for an unknown or not listable entity.
	 */
	public function GetObjects(Request $request, Response $response, array $args)
	{
		if (!EntityReadPolicy::Covers($args['entity']) || !$this->IsValidExposedEntity($args['entity']) || $this->IsEntityWithNoListing($args['entity']))
		{
			return $this->GenericErrorResponse($response, 'Entity does not exist or is not exposed');
		}
		EntityReadPolicy::Check($request, $args['entity']);
		$this->AssertWholeObjectReadable($request, $args['entity']);

		$queryParams = $request->getQueryParams();
		$source = $this->DB->{$args['entity']}();
		if ($args['entity'] === 'locations')
		{
			// The generation is exposed only by the additive label context route.
			$source = $source->select('id, name, description, row_created_timestamp, is_freezer, active, parent_location_id, storage_class_id, tare_weight, tare_qu_id');
		}
		$objects = $this->MaterialiseFiltered($request, $this->QueryData($request, $source, $queryParams), $queryParams);

		$userfields = UserfieldsService::GetInstance()->GetFields($args['entity']);
		if (count($userfields) > 0)
		{
			$allUserfieldValues = UserfieldsService::GetInstance()->GetAllValues($args['entity']);

			foreach ($objects as $object)
			{
				$userfieldKeyValuePairs = null;
				foreach ($userfields as $userfield)
				{
					// TODO: Handle this somehow more generically
					$userfieldReference = 'id';
					if ($args['entity'] == 'stock')
					{
						$userfieldReference = 'stock_id';
					}

					$value = FindObjectInArrayByPropertyValue(FindAllObjectsInArrayByPropertyValue($allUserfieldValues, 'object_id', $object->{$userfieldReference}), 'name', $userfield->name);
					if ($value)
					{
						$userfieldKeyValuePairs[$userfield->name] = $value->value;
					}
					else
					{
						$userfieldKeyValuePairs[$userfield->name] = null;
					}
				}

				$object->userfields = $userfieldKeyValuePairs;
			}
		}

		$objects = FieldPolicy::GetInstance()->RedactRows($args['entity'], $objects);

		return $this->ApiResponse($response, $objects);
	}

	/**
	 * GET /api/userfields/{entity}/{objectId} - returns the Userfield values of the
	 * given object as a key/value map (200) or a 400 error response.
	 */
	public function GetUserfields(Request $request, Response $response, array $args)
	{
		// The current-user profile remains readable without household user-directory access.
		if (!EntityReadPolicy::Covers($args['entity']))
		{
			return $this->GenericErrorResponse($response, 'Entity does not exist or is not exposed');
		}
		if ($args['entity'] !== 'users' || (string)$args['objectId'] !== (string)VICTUAL_USER_ID)
		{
			EntityReadPolicy::Check($request, $args['entity']);
		}
		return $this->HandleApiCall($response, function () use ($args, $response)
		{
			return $this->ApiResponse($response, UserfieldsService::GetInstance()->GetValues($args['entity'], $args['objectId']));
		});
	}

	/**
	 * PUT /api/userfields/{entity}/{objectId} - sets the Userfield values of the given
	 * object from the JSON request body (a key/value map).
	 * Requires the MASTER_DATA_EDIT permission (403 otherwise).
	 * Returns 204 on success or a 400 error response.
	 */
	public function SetUserfields(Request $request, Response $response, array $args)
	{
		User::CheckPermission($request, User::PERMISSION_MASTER_DATA_EDIT);

		$requestBody = $this->GetParsedAndFilteredRequestBody($request);

		return $this->HandleApiCall($response, function () use ($args, $requestBody, $response)
		{
			if ($requestBody === null)
			{
				throw new \Exception('Request body could not be parsed (probably invalid JSON format or missing/wrong Content-Type header)');
			}

			UserfieldsService::GetInstance()->SetValues($args['entity'], $args['objectId'], $requestBody);
			return $this->EmptyApiResponse($response);
		});
	}

	/**
	 * Whether editing the given entity additionally requires the ADMIN permission (per OpenAPI spec enum).
	 */
	/**
	 * The request body with the columns the server owns removed.
	 *
	 * AddObject() and EditObject() hand the parsed body straight to LessQL's createRow()
	 * and update(), which write whatever keys it contains - so any account that may edit
	 * master data could rewrite a row's primary key and its creation timestamp on every
	 * exposed entity (sweep finding S16). Rewriting an id relocates a row out from under
	 * every foreign key that names it; rewriting row_created_timestamp rewrites history.
	 *
	 * A blocklist of two rather than a per-entity allowlist derived from the spec's entity
	 * schemas, deliberately and for now: the allowlist is only correct if those schemas are
	 * complete, which has never been tested. Plan 11 question 5 parks it behind
	 * plan 14 piece 2, which is what will make them trustworthy.
	 *
	 * The keys are dropped rather than refused, so a client that reads an object, edits one
	 * field and PUTs the whole thing back - which is what the fork's own forms do - keeps
	 * working.
	 *
	 * @param array $requestBody The parsed and purified request body
	 * @return array
	 */
	private static function WithoutServerOwnedColumns(array $requestBody): array
	{
		foreach (self::SERVER_OWNED_COLUMNS as $column)
		{
			unset($requestBody[$column]);
		}

		return $requestBody;
	}

	/**
	 * Columns of an exposed entity that no client may write through the generic CRUD
	 * endpoints, whatever permission it holds. See WithoutServerOwnedColumns().
	 */
	private const SERVER_OWNED_COLUMNS = ['id', 'row_created_timestamp', 'import_epoch'];

	/**
	 * Plan 23 questions 1 and 2: is_freezer is derived from the chosen storage class, and
	 * the derivation lives here rather than in a trigger, because the importer - the only
	 * other writer of this table - never sets a class at all (bin/victual-db-import reads
	 * upstream grocy SQLite, which has no storage_classes concept), so a trigger would fire
	 * on no rows.
	 *
	 * A request body that sets storage_class_id (to anything but null) has is_freezer
	 * overwritten from that class's treats_as_freezer, regardless of what the same request
	 * otherwise submits for is_freezer - the class becomes the sole writer from that point
	 * on, which is what keeps the two from silently disagreeing about the same physical
	 * fact. A body that leaves storage_class_id absent, or sets it to null, leaves
	 * is_freezer exactly as submitted: an unclassified location keeps that flag
	 * independently editable, per question 3's answer that a location may have no class.
	 *
	 * An unresolvable storage_class_id (deleted between the picker loading and the request
	 * landing, or simply invalid) is left alone here and falls through to the write itself,
	 * which the FOREIGN KEY on locations.storage_class_id refuses.
	 */
	private function WithDerivedIsFreezer(array $requestBody): array
	{
		if (!array_key_exists('storage_class_id', $requestBody) || $requestBody['storage_class_id'] === null)
		{
			return $requestBody;
		}

		$storageClass = $this->DB->storage_classes($requestBody['storage_class_id']);
		if ($storageClass !== null)
		{
			$requestBody['is_freezer'] = $storageClass->treats_as_freezer;
		}

		return $requestBody;
	}

	/**
	 * ADR-0022 decisions 4 and 7 (2026-09-14), question 1's decided answer: the product-level
	 * tare mechanism is retired, `enable_tare_weight_handling` and `tare_weight` stay on the
	 * wire at their current values, and *enabling* the flag from here on answers 400 naming
	 * the per-entry (docs/plans/landed/28-open-container-measurement.md) or per-location
	 * (docs/plans/landed/29-working-container-replenishment.md) tare that replaced it.
	 *
	 * Only the 0 -> 1 transition is refused. A product that already has the flag enabled can
	 * still be saved unchanged - this is a business rule about what a client may newly
	 * choose, not a constraint on data that predates the retirement, and `products` carries
	 * no CHECK of its own for the same reason plan 28's spike gives for convertibility
	 * (.spike-adr22/RESULTS.md#prerequisite-7-conversion-failure): the fact being refused is
	 * not a property of the row being written, it is a property of the write itself.
	 *
	 * @param array $requestBody The parsed, purified, server-owned-column-stripped request body
	 * @param bool $currentlyEnabled Whether the row already has the flag enabled (false for AddObject)
	 * @throws EInvalidApiQuery When the body sets the flag to a truthy value it was not already at
	 */
	private function RefuseTareEnable(array $requestBody, bool $currentlyEnabled): void
	{
		if (!array_key_exists('enable_tare_weight_handling', $requestBody))
		{
			return;
		}

		if (boolval($requestBody['enable_tare_weight_handling']) && !$currentlyEnabled)
		{
			throw new EInvalidApiQuery('enable_tare_weight_handling can no longer be enabled - weigh an opened purchased container on the stock entry instead (docs/plans/landed/28-open-container-measurement.md), or a refillable vessel on its location (docs/plans/landed/29-working-container-replenishment.md)');
		}
	}

	private function IsEntityWithEditRequiresAdmin($entity)
	{
		return in_array($entity, $this->GetOpenApispec()->components->schemas->ExposedEntityEditRequiresAdmin->enum);
	}

	/**
	 * Whether the given entity is excluded from listing/reading (per OpenAPI spec enum).
	 */
	private function IsEntityWithNoListing($entity)
	{
		return in_array($entity, $this->GetOpenApispec()->components->schemas->ExposedEntityNoListing->enum);
	}

	/**
	 * Whether the given entity cannot be created/edited through this API (per OpenAPI spec enum).
	 */
	private function IsEntityWithNoEdit($entity)
	{
		return in_array($entity, $this->GetOpenApispec()->components->schemas->ExposedEntityNoEdit->enum);
	}

	/**
	 * Whether the given entity cannot be deleted through this API (per OpenAPI spec enum).
	 */
	private function IsEntityWithNoDelete($entity)
	{
		return in_array($entity, $this->GetOpenApispec()->components->schemas->ExposedEntityNoDelete->enum);
	}

	/**
	 * Whether the given entity is exposed through this API at all (per OpenAPI spec enum).
	 */
	private function IsValidExposedEntity($entity)
	{
		return in_array($entity, $this->GetOpenApispec()->components->schemas->ExposedEntity->enum);
	}
}
