<?php

// Uses a disposable schema, never the configured application's tables.
// LABEL_TEST_DSN='pgsql:host=...;dbname=...' PGUSER=... PGPASSWORD=... php ...
define('VICTUAL_ROOT_PATH', dirname(__DIR__, 2));
spl_autoload_register(function ($class)
{
	$prefix = 'Victual\\Services\\';
	if (str_starts_with($class, $prefix))
	{
		require_once VICTUAL_ROOT_PATH . '/services/' . str_replace('\\', '/', substr($class, strlen($prefix))) . '.php';
	}
});

use Victual\Services\Labels\LabelIdentityService as Identity;
use Victual\Services\Database\DatabaseImporter;
use Victual\Services\Database\PostgresDialect;

/**
 * The highest migration number on disk.
 *
 * Hard-coded here until plan 27 added 0271, at which point this fixture started failing for
 * a reason that had nothing to do with what it tests: DatabaseImporter compares what the
 * target recorded against what the code ships, so a fixture claiming an older number is
 * refused before the guard under test ever runs.
 */
function LatestMigrationNumber(): int
{
	$highest = 0;
	foreach (glob(VICTUAL_ROOT_PATH . '/migrations/*') as $file)
	{
		// DOALWAYS_MIGRATION_ID (8888) runs on every boot and is not part of the sequence
		// GetLatestMigrationNumber() reports, so it is excluded here for the same reason.
		if (preg_match('/^(\\d{4})\\./', basename($file), $matches)
			&& (int)$matches[1] !== \Victual\Services\DatabaseMigrationService::DOALWAYS_MIGRATION_ID)
		{
			$highest = max($highest, (int)$matches[1]);
		}
	}
	return $highest;
}

function Connect(string $schema): PDO
{
	$db = new PDO(getenv('LABEL_TEST_DSN'), getenv('PGUSER'), getenv('PGPASSWORD'), [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
	$db->exec('SET search_path TO ' . $schema);
	$db->exec("SET statement_timeout = '8s'");
	return $db;
}

function Import(PDO $db, ?callable $progress = null, bool $force = true): void
{
	$source = new PDO('sqlite::memory:');
	$source->exec("CREATE TABLE migrations (migration INTEGER); INSERT INTO migrations VALUES (265);
		CREATE TABLE locations (id INTEGER, name TEXT); INSERT INTO locations VALUES (1, 'Replacement')");
	(new DatabaseImporter($source, $db, new PostgresDialect(), $progress))->Import($force, false);
}

if (($argv[1] ?? '') === 'child')
{
	$db = Connect($argv[2]);
	$db->exec("SET application_name = '" . $argv[2] . "_child'");
	try
	{
		if ($argv[3] === 'import')
		{
			Import($db);
			echo 'imported';
		}
		elseif ($argv[3] === 'delete')
		{
			$db->exec('DELETE FROM locations WHERE id = 1');
			echo 'deleted';
		}
		else
		{
			$db->beginTransaction();
			echo (new Identity($db))->IssueLocation(1, (int)$argv[3]);
			$db->commit();
		}
	}
	catch (Throwable $e)
	{
		echo $e->getMessage();
	}
	exit;
}

$checks = 0;
function Check(bool $ok, string $message): void
{
	global $checks;
	if (!$ok) { throw new RuntimeException($message); }
	$checks++;
}

function Refused(callable $work, string $message): void
{
	try { $work(); } catch (Throwable $e)
	{
		Check(str_contains($e->getMessage(), $message), 'Unexpected refusal: ' . $e->getMessage());
		return;
	}
	throw new RuntimeException('Expected refusal: ' . $message);
}

function Child(PDO $db, string $schema, string $operation, string $event = 'advisory'): array
{
	$process = proc_open([PHP_BINARY, __FILE__, 'child', $schema, $operation], [1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
	$deadline = microtime(true) + 5;
	do
	{
		$db->query('SELECT pg_stat_clear_snapshot()')->fetchColumn();
		$query = $db->query("SELECT count(*) FROM pg_stat_activity WHERE application_name = '{$schema}_child' AND wait_event = '$event'");
		if ((int)$query->fetchColumn() === 1) { return [$process, $pipes]; }
		usleep(10000);
	} while (microtime(true) < $deadline);
	throw new RuntimeException('Concurrent operation did not block on the shared lock');
}

function Finish(array $child): string
{
	[$process, $pipes] = $child;
	$output = stream_get_contents($pipes[1]);
	$error = stream_get_contents($pipes[2]);
	fclose($pipes[1]); fclose($pipes[2]);
	Check(proc_close($process) === 0 && $error === '', 'Child failed: ' . $error);
	return $output;
}

$schema = 'label_test_' . bin2hex(random_bytes(6));
$cachePath = sys_get_temp_dir() . '/' . $schema;
$db = Connect($schema);
try
{
	$db->exec('CREATE SCHEMA ' . $schema);
	$db->exec("CREATE TABLE locations (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, active SMALLINT DEFAULT 1);
		CREATE TABLE migrations (migration INTEGER); INSERT INTO migrations VALUES (" . LatestMigrationNumber() . ");
		INSERT INTO locations (name) VALUES ('Original')");
	$db->exec(file_get_contents(VICTUAL_ROOT_PATH . '/migrations/0269.pgsql.sql'));
	$db->exec('CREATE TABLE api_keys(id INTEGER PRIMARY KEY)');
	$db->exec(file_get_contents(VICTUAL_ROOT_PATH . '/migrations/0259.pgsql.sql'));
	$db->exec(file_get_contents(VICTUAL_ROOT_PATH . '/migrations/0270.pgsql.sql'));
	$db->exec("INSERT INTO label_workers(name,configuration_mode) VALUES('retained worker','paired');
		INSERT INTO label_worker_sessions(worker_id,created_by_user_id,pairing_material_hash,material_expires_at) VALUES(1,42,'fixture',CURRENT_TIMESTAMP+INTERVAL '1 hour')");
	$identity = new Identity($db);

	// Negative control FIRST: the original precheck window, including a real issuance.
	Check((int)$db->query('SELECT count(*) FROM labels')->fetchColumn() === 0, 'Precheck sees no labels');
	$db->beginTransaction(); $uid = $identity->IssueLocation(1, 0); $db->commit();
	$db->exec("TRUNCATE locations RESTART IDENTITY CASCADE; INSERT INTO locations (name) VALUES ('Replacement')");
	Check($identity->Resolve($uid, true)['target']['name'] === 'Replacement', 'Negative control must reproduce label aliasing');
	$db->exec("TRUNCATE labels; UPDATE locations SET name = 'Original'");

	$uids = [];
	for ($i = 0; $i < 10000; $i++)
	{
		$value = Identity::GenerateUid();
		Check((bool)preg_match('/^[0-9A-F][0-9A-HJKMNP-TV-Z]{12}$/D', $value), '64-bit Crockford encoding');
		$uids[$value] = true;
	}
	Check(count($uids) === 10000, 'No duplicate random uids');
	Check(Identity::Canonicalize('vCtL:oill000000000') === '0111000000000', 'Decode aliases and case');
	foreach (['', 'grcy:l:1', '000000000000U', 'Z000000000000', '0000000000000\n'] as $bad)
	{
		Check(Identity::Canonicalize($bad) === null, 'Reject malformed uid');
	}
	Refused(fn() => $identity->IssueLocation(1, 0), 'requires a transaction');
	$db->beginTransaction(); $uid = $identity->IssueLocation(1, 0); $db->rollBack();
	Check($identity->Resolve($uid, true) === ['status' => 'unknown'], 'Rollback removes identity');
	$db->beginTransaction(); $uid = $identity->IssueLocation(1, 0); $db->commit();
	$db->beginTransaction(); Check($identity->IssueLocation(1, 0) === $uid, 'Repeated issuance shares live uid'); $db->commit();
	Check($identity->Resolve('VCTL:' . strtolower($uid), true)['target']['name'] === 'Original', 'Live resolution');
	Check($identity->Resolve($uid, false) === $identity->Resolve('0000000000000', false), 'Denied known and unknown match');
	// A denied lookup must not even touch the label table, regardless of existence.
	$db->beginTransaction(); $db->exec('ALTER TABLE labels RENAME TO hidden_labels');
	Check($identity->Resolve($uid, false) === ['status' => 'unknown'], 'Denied lookup performs no label query'); $db->rollBack();
	$db->exec("UPDATE locations SET active = 0, name = 'Renamed' WHERE id = 1");
	Check($identity->Resolve($uid, true)['target']['name'] === 'Renamed', 'Rename and deactivation preserve identity');
	Refused(fn() => Import($db), '1 live label(s)');
	Refused(fn() => Import($db, null, false), '1 live label(s)');
	Check($identity->LocationContext(1)['import_epoch'] === 0, 'Refused import preserves epoch');

	// Actual importer waits on an in-flight issuance, then refuses after it commits.
	$db->beginTransaction(); Identity::LockImport($db);
	$child = Child($db, $schema, 'import'); $db->commit();
	Check(str_contains(Finish($child), '1 live label(s)'), 'Concurrent import refuses live label');
	$db->beginTransaction(); $db->exec('DELETE FROM locations WHERE id = 1'); $db->rollBack();
	Check($identity->Resolve($uid, true)['status'] === 'resolved', 'Delete rollback also undoes retirement');
	$db->exec('DELETE FROM locations WHERE id = 1');
	$retired = $identity->Resolve($uid, true);
	Check($retired['status'] === 'retired' && $retired['snapshot']['name'] === 'Renamed', 'Hard delete captures last historical name');
	Import($db);
	Check($identity->Resolve($uid, true) === $retired, 'Retired snapshot survives actual import');
	Check($identity->LocationContext(1)['import_epoch'] === 1, 'Import advances location epoch');
	$db->beginTransaction(); Refused(fn() => $identity->IssueLocation(1, 0), 'epoch 0 -> 1'); $db->rollBack();

	// Import wins: the waiting issuance must use its old request epoch, not the new row.
	$child = null;
	Import($db, function ($message) use ($db, $schema, &$child)
	{
		if (preg_match('/^  locations\s+1 rows$/', $message))
		{
			$child = Child($db, $schema, '1');
		}
	});
	Check(str_contains(Finish($child), 'epoch 1 -> 2'), 'Waiting stale issuance mints nothing');
	Check((int)$db->query('SELECT count(*) FROM labels WHERE retired_at IS NULL')->fetchColumn() === 0, 'No stale mapping');

	// Force a primary-key collision, then exercise the real retry inside the transaction.
	$collision = new class($db, $uid) extends Identity
	{
		private int $calls = 0;
		public function __construct(PDO $db, private string $duplicate) { parent::__construct($db); }
		protected function NewUid(): string { return $this->calls++ === 0 ? $this->duplicate : parent::NewUid(); }
	};
	$db->beginTransaction(); $newUid = $collision->IssueLocation(1, 2); $db->commit();
	Check($newUid !== $uid && $identity->Resolve($newUid, true)['target']['name'] === 'Replacement', 'Collision retries and reused target gets new uid');
	Refused(fn() => $db->exec("INSERT INTO labels (uid, kind, target_id) VALUES ('0000000000000', 'location', 1)"), 'labels_one_live_per_target');
	Check($identity->Resolve($uid, true) === $retired, 'Reused target never revives retired uid');

	$db->beginTransaction(); $identity->IssueLocation(1, 2);
	$child = Child($db, $schema, 'delete', 'transactionid'); $db->commit();
	Check(Finish($child) === 'deleted' && $identity->Resolve($newUid, true)['status'] === 'retired', 'Delete waits for issuance and retires it');
	$db->exec("INSERT INTO locations (id, name) VALUES (1, 'Fourth')");
	$db->beginTransaction(); $db->exec('DELETE FROM locations WHERE id = 1');
	$child = Child($db, $schema, '2', 'transactionid'); $db->commit();
	Check(str_contains(Finish($child), 'Location not found'), 'Issuance waits for deletion and refuses');
	Check((int)$db->query('SELECT count(*) FROM labels WHERE retired_at IS NULL')->fetchColumn() === 0, 'Concurrent deletion leaves no dangling live label');

	// Exercise the HTTP controllers with the same connection and real permission helper.
	$loader = require VICTUAL_ROOT_PATH . '/packages/autoload.php';
	define('VICTUAL_USER_ID', 1);
	define('VICTUAL_DATAPATH', sys_get_temp_dir());
	mkdir($cachePath, 0700);
	define('VICTUAL_VIEWCACHE_PATH', $cachePath);
	define('VICTUAL_MODE', 'production');
	require VICTUAL_ROOT_PATH . '/config-dist.php';
	$lessql = new LessQL\Database($db);
	$lessql->setIdentifierDelimiter('"');
	foreach (['DbConnectionRaw' => $db, 'DbConnection' => $lessql] as $property => $value)
	{
		(new ReflectionProperty(Victual\Services\DatabaseService::class, $property))->setValue(null, $value);
	}
	$db->exec("CREATE TABLE user_permissions_resolved (id INTEGER, user_id INTEGER, permission_name TEXT);
		INSERT INTO user_permissions_resolved VALUES (1, 1, 'STOCK_VIEW');
		ALTER TABLE locations ADD COLUMN description TEXT;
		ALTER TABLE locations ADD COLUMN row_created_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
		ALTER TABLE locations ADD COLUMN is_freezer SMALLINT DEFAULT 0;
		ALTER TABLE locations ADD COLUMN parent_location_id INTEGER;
		CREATE TABLE userfields (id INTEGER, entity TEXT, sort_number INTEGER, name TEXT);
		CREATE TABLE userentities (id INTEGER, name TEXT);
		CREATE COLLATION nocase (provider = libc, locale = 'C');
		CREATE TABLE userfield_values (id INTEGER, field_id INTEGER, object_id INTEGER, value TEXT);
		CREATE TABLE userfield_values_resolved (id INTEGER, entity TEXT, object_id INTEGER, name TEXT, value TEXT);
		INSERT INTO locations (id, name) VALUES (1, 'API shelf')");
	$container = new DI\Container(); $container->set('view', null);
	$controller = new Victual\Controllers\Api\LabelsApiController($container);
	$request = (new Slim\Psr7\Factory\ServerRequestFactory())->createServerRequest('GET', '/');
	$db->beginTransaction(); $apiUid = $identity->IssueLocation(1, 2); $db->commit();
	$reply = $controller->Resolve($request, new Slim\Psr7\Response(), ['code' => 'vctl:' . $apiUid]);
	Check($reply->getStatusCode() === 200 && json_decode((string)$reply->getBody(), true)['status'] === 'resolved', 'Authorized HTTP resolution: ' . (string)$reply->getBody());
	$reply = $controller->LocationContext($request, new Slim\Psr7\Response(), ['locationId' => '1']);
	Check(json_decode((string)$reply->getBody(), true)['import_epoch'] === 2, 'HTTP context carries epoch');
	$generic = new Victual\Controllers\Api\GenericEntityApiController($container);
	foreach (['GetObject' => ['entity' => 'locations', 'objectId' => 1], 'GetObjects' => ['entity' => 'locations']] as $method => $args)
	{
		$reply = $generic->$method($request, new Slim\Psr7\Response(), $args);
		Check($reply->getStatusCode() === 200 && !str_contains((string)$reply->getBody(), 'import_epoch'), 'Existing ' . $method . ' response excludes epoch');
	}
	$db->exec("INSERT INTO user_permissions_resolved VALUES (2, 1, 'MASTER_DATA_EDIT')");
	$edit = $request->withMethod('PUT')->withHeader('Content-Type', 'application/json')->withParsedBody(['name' => 'Edited shelf', 'import_epoch' => 999]);
	$reply = $generic->EditObject($edit, new Slim\Psr7\Response(), ['entity' => 'locations', 'objectId' => 1]);
	Check($reply->getStatusCode() === 204 && $identity->LocationContext(1)['import_epoch'] === 2, 'Generic edit cannot forge import epoch');
	$db->exec('DELETE FROM locations WHERE id = 1');
	$reply = $controller->Resolve($request, new Slim\Psr7\Response(), ['code' => $apiUid]);
	Check(json_decode((string)$reply->getBody(), true)['status'] === 'retired', 'HTTP retirement is distinct');
	$reply = $controller->Resolve($request, new Slim\Psr7\Response(), ['code' => '0000000000000']);
	Check((string)$reply->getBody() === '{"status":"unknown"}', 'HTTP unknown is distinct');
	$db->exec('DELETE FROM user_permissions_resolved');
	$denied = $controller->Resolve($request, new Slim\Psr7\Response(), ['code' => $apiUid]);
	$unknown = $controller->Resolve($request, new Slim\Psr7\Response(), ['code' => '0000000000000']);
	Check($denied->getStatusCode() === $unknown->getStatusCode() && (string)$denied->getBody() === (string)$unknown->getBody(), 'HTTP denied existence is indistinguishable');
	Check($db->query('SELECT revoked_reason FROM label_worker_sessions WHERE worker_id=1')->fetchColumn() === 'admin', 'Import invalidates pairing material bound to replaced users');
	echo "PASS: $checks label identity assertions, including precheck negative control and concurrent import/issuance\n";
}
finally
{
	if ($db->inTransaction()) { $db->rollBack(); }
	$db->exec('DROP SCHEMA ' . $schema . ' CASCADE');
	if (is_dir($cachePath))
	{
		$entries = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($cachePath, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
		foreach ($entries as $entry)
		{
			$entry->isDir() ? rmdir($entry->getPathname()) : unlink($entry->getPathname());
		}
		rmdir($cachePath);
	}
}
