<?php
// Shared disposable fixture. Never points the application's singleton at production data.
require_once dirname(__DIR__,2).'/packages/autoload.php';
use Victual\Services\Labels\{DriverRegistryService,PrinterConfigurationService,PrintAttemptService};
function labelDb(string $schema): PDO
{
 $db=new PDO(getenv('LABEL_TEST_DSN'),getenv('PGUSER'),getenv('PGPASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
 $db->exec('SET search_path TO '.$schema);$db->exec("SET statement_timeout='8s'");return $db;
}
function fixture(PDO $db): void
{
 $db->exec("CREATE TABLE locations(id INTEGER PRIMARY KEY,name TEXT NOT NULL); INSERT INTO locations VALUES(1,'Pantry');
 CREATE TABLE api_keys(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,api_key TEXT UNIQUE NOT NULL,key_hint TEXT,user_id INTEGER,expires TIMESTAMP,key_type TEXT,description TEXT);");
 foreach (['0259','0269','0270'] as $migration) $db->exec(file_get_contents(dirname(__DIR__,2).'/migrations/'.$migration.'.pgsql.sql'));
}
function driver(): array
{
 return json_decode(file_get_contents(__DIR__.'/fixtures/brother-ql.json'),true,512,JSON_THROW_ON_ERROR);
}
function printer(int $worker): array
{
 return ['name'=>'Test printer','worker_id'=>$worker,'driver_id'=>'brother.ql','driver_schema_version'=>'1.0','connection'=>'127.0.0.1:9100','connection_type'=>'tcp','model'=>'QL-820NWBc','settings'=>['media'=>'62red','resolution_x'=>300,'resolution_y'=>300,'color_mode'=>'black_red']];
}
function tx(PDO $db,callable $call): mixed
{
 $db->beginTransaction();try{$result=$call();$db->commit();return $result;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function check(bool $condition,string $message): void
{global $assertions;if(!$condition)throw new RuntimeException($message);$assertions++;}
function refused(callable $call,string $code): void
{
 try{$call();throw new RuntimeException('Expected refusal '.$code);}catch(Victual\Services\Labels\LabelValidationException $e){check($e->errorCode===$code,'Refusal '.$code.' got '.$e->errorCode);}
}
function seed(PDO $db): array
{
 $worker=(int)$db->query("INSERT INTO label_workers(name,configuration_mode) VALUES('fixture','declared') RETURNING id")->fetchColumn();
 tx($db,fn()=>(new DriverRegistryService($db))->Register($worker,[driver()]));
 $printer=tx($db,fn()=>(new PrinterConfigurationService($db))->Save(printer($worker)));return [$worker,$printer];
}
class ReadyAttempts extends PrintAttemptService
{
 protected function ArtifactReady(array $job): bool{return true;}
}
function runLabelTests(callable $tests): void
{
 global $assertions;$assertions=0;$schema='label_test_'.bin2hex(random_bytes(8));$db=labelDb('public');$db->exec('CREATE SCHEMA '.$schema);
 try{$db=labelDb($schema);fixture($db);$tests($db,$schema);echo 'PASS '.$assertions." assertions\n";}
 finally{if($db->inTransaction())$db->rollBack();$db->exec('DROP SCHEMA '.$schema.' CASCADE');}
}
