<?php
// Shared disposable fixture. Never points the application's singleton at production data.
require_once dirname(__DIR__,2).'/packages/autoload.php';
use Victual\Services\Labels\{ArtifactService,DriverRegistryService,LabelTemplateService,MediaProfileService,PrinterConfigurationService,PrintAttemptService,RenderRequestService,LabelOperationsService};
function labelDb(string $schema): PDO
{
 $db=new PDO(getenv('LABEL_TEST_DSN'),getenv('PGUSER'),getenv('PGPASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
 $db->exec('SET search_path TO '.$schema);$db->exec("SET statement_timeout='8s'");return $db;
}
function fixture(PDO $db): void
{
 $db->exec("CREATE TABLE locations(id INTEGER PRIMARY KEY,name TEXT NOT NULL,description TEXT); INSERT INTO locations VALUES(1,'Pantry','The tall one');
 CREATE TABLE api_keys(id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,api_key TEXT UNIQUE NOT NULL,key_hint TEXT,user_id INTEGER,expires TIMESTAMP,key_type TEXT,description TEXT);");
 foreach (['0258','0259','0269','0270','0271','0272'] as $migration) $db->exec(file_get_contents(dirname(__DIR__,2).'/migrations/'.$migration.'.pgsql.sql'));
}
function driver(): array
{
 return json_decode(file_get_contents(__DIR__.'/fixtures/brother-ql.json'),true,512,JSON_THROW_ON_ERROR);
}
function printer(int $worker): array
{
 return ['name'=>'Test printer','worker_id'=>$worker,'driver_id'=>'brother.ql','driver_schema_version'=>'1.0','connection'=>'127.0.0.1:9100','connection_type'=>'tcp','model'=>'QL-820NWBc','settings'=>['media'=>'62red','resolution_x'=>300,'resolution_y'=>300,'color_mode'=>'black_red']];
}
function tx(PDO $db,callable $call): mixed
{
 $db->beginTransaction();try{$result=$call();$db->commit();return $result;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function check(bool $condition,string $message): void
{global $assertions;if(!$condition)throw new RuntimeException($message);$assertions++;}
function refused(callable $call,string $code): void
{
 try{$call();throw new RuntimeException('Expected refusal '.$code);}catch(Victual\Services\Labels\LabelValidationException $e){check($e->errorCode===$code,'Refusal '.$code.' got '.$e->errorCode);}
}
function seed(PDO $db): array
{
 $worker=(int)$db->query("INSERT INTO label_workers(name,configuration_mode) VALUES('fixture','declared') RETURNING id")->fetchColumn();
 tx($db,fn()=>(new DriverRegistryService($db))->Register($worker,[driver()]));
 $printer=tx($db,fn()=>(new PrinterConfigurationService($db))->Save(printer($worker)));
 return [$worker,$printer,seedTemplate($db)];
}

/**
 * Enqueue, render, attach - the whole path a claimable job actually takes.
 *
 * Group B's suites used to call Enqueue() and rely on a subclass that answered "ready" for
 * every job. That override is gone, so a test that wants a claimable job now has to produce
 * an artifact the same way production does. Which is the point: the readiness these suites
 * exercise is the readiness that ships.
 */
function issued(PDO $db,\Victual\Services\Labels\LabelPrintJobService $jobs,int $printer): int
{
 $id=tx($db,fn()=>$jobs->Enqueue(1,0,$printer));renderAndAttach($db,$id);return $id;
}
/**
 * Named for what it used to do. Plan 27 made artifact readiness a real condition, so this no
 * longer overrides anything - a job is claimable here for exactly the reason it is claimable
 * in production, because renderFor() actually produced and Victual actually verified an
 * artifact. The class survives so the lock-clause child mode below still has something to
 * extend.
 */
class ReadyAttempts extends PrintAttemptService
{
}

/** A QR-only template, so a fixture needs no font asset to be a real published template. */
function seedTemplate(PDO $db): int
{
 $templates=new LabelTemplateService($db);
 $template=tx($db,fn()=>$templates->Create('Fixture location label',null,'location',null));
 $draft=$templates->GetDraft((int)$template['id']);
 $document=['schema_version'=>1,'entity_kind'=>'location',
  'canvas'=>['width_mm'=>62.0,'height_mm'=>30.0,'max_height_mm'=>null,'margins_mm'=>['top'=>1.0,'right'=>1.0,'bottom'=>1.0,'left'=>1.0]],
  'elements'=>[['type'=>'qr','id'=>'code','x_mm'=>2.0,'y_mm'=>2.0,'module_mm'=>0.6,'ec_level'=>'M','quiet_zone_modules'=>4,'color'=>'black','source'=>'label.payload']]];
 tx($db,fn()=>$templates->SaveDraft((int)$template['id'],$document,$draft['revision_token'],null));
 tx($db,fn()=>$templates->Publish((int)$template['id'],null));
 return (int)$template['id'];
}

/**
 * The renderer, as a fixture.
 *
 * It does exactly what the real one will: claim a durable request, read the resolved input,
 * paint the module matrix Victual computed at the geometry the profile fixes, and submit
 * indexed PNG bytes. Nothing here is a shortcut past verification - ArtifactService checks
 * these bytes the same way it will check the Rust renderer's.
 */
function renderPending(PDO $db,string $rendererId='fixture-renderer'): ?array
{
 $requests=new RenderRequestService($db);
 $input=tx($db,fn()=>$requests->Claim());
 if($input===null)return null;
 $bytes=paintArtifact($input);
 return tx($db,fn()=>(new ArtifactService($db))->Accept($input['render_request_id'],$input['generation_token'],$bytes,$rendererId,'0.0.1-fixture'));
}

/** Renders whatever is pending and attaches it to the job that was waiting for it. */
function renderAndAttach(PDO $db,int $jobId): array
{
 $artifact=renderPending($db);
 if($artifact===null)throw new RuntimeException('No render request was pending');
 tx($db,fn()=>(new LabelOperationsService($db))->AttachArtifact((int)$artifact['render_request_id'],(int)$artifact['id']));
 return $artifact;
}

/** Paints the resolved render input as a conforming raster/png-indexed;v=1 artifact. */
function paintArtifact(array $input,?callable $mutate=null): string
{
 $profile=$input['profile'];$document=$input['document'];
 $width=(int)$profile['raster_width_px'];
 $dpiX=(int)$profile['dpi_x'];$dpiY=(int)$profile['dpi_y'];
 $heightMm=$document['canvas']['height_mm']??$document['canvas']['max_height_mm'];
 $height=(int)round($heightMm*$dpiY/25.4);
 $palette=$profile['pixel_policy']['palette'];
 $white=array_search('#ffffff',$palette,true);$black=array_search('#000000',$palette,true);
 $pixels=array_fill(0,$height,array_fill(0,$width,$white));
 foreach($document['elements'] as $element)
 {
  if($element['type']!=='qr')continue;
  $matrix=$input['qr'][$element['id']];
  $mx=(int)round($element['module_mm']*$dpiX/25.4);$my=(int)round($element['module_mm']*$dpiY/25.4);
  $ox=(int)round($element['x_mm']*$dpiX/25.4)+$element['quiet_zone_modules']*$mx;
  $oy=(int)round($element['y_mm']*$dpiY/25.4)+$element['quiet_zone_modules']*$my;
  for($r=0;$r<$matrix['size'];$r++)for($c=0;$c<$matrix['size'];$c++)
  {
   if($matrix['modules'][$r][$c]!=='1')continue;
   for($dy=0;$dy<$my;$dy++)for($dx=0;$dx<$mx;$dx++)
   {
    $y=$oy+$r*$my+$dy;$x=$ox+$c*$mx+$dx;
    if($y<$height&&$x<$width)$pixels[$y][$x]=$black;
   }
  }
 }
 if($mutate!==null)$mutate($pixels,$width,$height);
 return encodeIndexedPng($pixels,$width,$height,$palette);
}

/** A minimal colour-type-3, bit-depth-2 PNG encoder. */
function encodeIndexedPng(array $pixels,int $width,int $height,array $palette): string
{
 $chunk=function(string $type,string $data){return pack('N',strlen($data)).$type.$data.pack('N',crc32($type.$data));};
 $ihdr=pack('NN',$width,$height).chr(2).chr(3).chr(0).chr(0).chr(0);
 $plte='';foreach($palette as $colour)$plte.=hex2bin(substr($colour,1));
 $raw='';
 foreach($pixels as $row)
 {
  $line='';$acc=0;$filled=0;
  foreach($row as $index)
  {
   $acc=($acc<<2)|($index&3);$filled++;
   if($filled===4){$line.=chr($acc);$acc=0;$filled=0;}
  }
  if($filled>0)$line.=chr($acc<<(2*(4-$filled)));
  $raw.=chr(0).$line;
 }
 return "\x89PNG\r\n\x1a\n".$chunk('IHDR',$ihdr).$chunk('PLTE',$plte).$chunk('IDAT',gzcompress($raw,9)).$chunk('IEND','');
}
function runLabelTests(callable $tests): void
{
 global $assertions;$assertions=0;$schema='label_test_'.bin2hex(random_bytes(8));$db=labelDb('public');$db->exec('CREATE SCHEMA '.$schema);
 try{$db=labelDb($schema);fixture($db);$tests($db,$schema);echo 'PASS '.$assertions." assertions\n";}
 finally{if($db->inTransaction())$db->rollBack();$db->exec('DROP SCHEMA '.$schema.' CASCADE');}
}
