-- ADR-0021 prerequisite 4: a reprint replays retained bytes and never rerenders.
DROP SCHEMA IF EXISTS adr21r CASCADE;
CREATE SCHEMA adr21r;
SET search_path TO adr21r;

CREATE TABLE artifacts (
    artifact_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_uid    text NOT NULL,
    form         text NOT NULL,
    combination  jsonb NOT NULL,
    bytes        bytea,               -- NULL once collected
    sha256       text NOT NULL,       -- kept after collection, so a refusal can name it
    byte_length  integer NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    collected_at timestamptz
);

CREATE TABLE print_jobs (
    job_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label_uid    text NOT NULL,
    operation    text NOT NULL CHECK (operation IN ('first_issuance', 'reprint')),
    artifact_id  bigint NOT NULL REFERENCES artifacts (artifact_id),
    replays_job  bigint REFERENCES print_jobs (job_id),
    enqueued_at  timestamptz NOT NULL DEFAULT now(),
    outcome      text,
    evidence     jsonb
);

-- A reprint is a new job over the same artifact row. It never creates an artifact, so
-- there is no path through it that could reach a renderer.
CREATE OR REPLACE FUNCTION reprint(p_job bigint) RETURNS text LANGUAGE plpgsql AS $$
DECLARE a artifacts%ROWTYPE; src print_jobs%ROWTYPE; new_id bigint;
BEGIN
    SELECT * INTO src FROM print_jobs WHERE job_id = p_job;
    IF NOT FOUND THEN RETURN 'refused: no such job'; END IF;
    SELECT * INTO a FROM artifacts WHERE artifact_id = src.artifact_id;
    IF a.collected_at IS NOT NULL OR a.bytes IS NULL THEN
        RETURN 'refused: artifact ' || a.artifact_id || ' (' || a.sha256 ||
               ') was collected on ' || to_char(a.collected_at, 'YYYY-MM-DD') ||
               '; an exact reprint has nothing to replay';
    END IF;
    INSERT INTO print_jobs (label_uid, operation, artifact_id, replays_job)
    VALUES (src.label_uid, 'reprint', a.artifact_id, src.job_id)
    RETURNING job_id INTO new_id;
    RETURN 'queued job ' || new_id;
END $$;
