-- Wave 3a. SQLite is frozen at 0265; this changes only the PostgreSQL runtime.
CREATE TABLE roles (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code TEXT NOT NULL UNIQUE,
 name TEXT NOT NULL UNIQUE,
 description TEXT,
 builtin SMALLINT NOT NULL DEFAULT 0 CHECK (builtin IN (0, 1)),
 row_created_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE role_permissions (
 role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
 permission_id INTEGER NOT NULL REFERENCES permission_hierarchy(id),
 PRIMARY KEY (role_id, permission_id)
);
CREATE TABLE user_roles (
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
 PRIMARY KEY (user_id, role_id)
);
CREATE OR REPLACE VIEW user_permissions_resolved AS
SELECT u.id AS id, u.id AS user_id, pt.name AS permission_name
FROM permission_tree pt CROSS JOIN users u
WHERE pt.id IN (
 SELECT permission_id FROM user_permissions WHERE user_id = u.id
 UNION
 SELECT rp.permission_id FROM user_roles ur JOIN role_permissions rp ON rp.role_id = ur.role_id
 WHERE ur.user_id = u.id
);

CREATE OR REPLACE VIEW uihelper_user_permissions AS
SELECT ph.id AS id, u.id AS user_id, ph.name AS permission_name, ph.id AS permission_id,
 CASE WHEN EXISTS (SELECT 1 FROM user_permissions_resolved pc
                   WHERE pc.user_id = u.id AND pc.permission_name = ph.name) THEN 1 ELSE 0 END AS has_permission,
 ph.parent AS parent,
 (SELECT string_agg(inherited.code, ',' ORDER BY inherited.code)
  FROM (SELECT DISTINCT r.code FROM user_roles ur
        JOIN roles r ON r.id = ur.role_id
        JOIN role_permissions rp ON rp.role_id = r.id
        JOIN permission_tree pt ON pt.id = rp.permission_id
        WHERE ur.user_id = u.id AND pt.name = ph.name) inherited) AS via_roles
FROM users u CROSS JOIN permission_hierarchy ph;

