-- Disposable spike for ADR-0023 acceptance prerequisites 2 and 3
-- (docs/adr/0023-taxonomy-is-groups-packaging-is-parent-product.md). Not part of plan 30's
-- migration 0279, which stays unwritten until that plan is scheduled — see
-- migrations/RESERVATIONS.md. This file exists only on the disposable spike branch.
--
-- product_groups and products as they stand in db/pgsql/baseline/01_tables.sql today,
-- trimmed to the columns this spike touches. Copied rather than sourced from the real
-- baseline so this spike has no dependency on the other 35 tables that file declares.

CREATE TABLE product_groups (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	description TEXT,
	row_created_timestamp TIMESTAMP DEFAULT date_trunc('second', LOCALTIMESTAMP),
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
);

CREATE TABLE products (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	product_group_id INTEGER,
	active SMALLINT NOT NULL DEFAULT 1 CHECK(active IN (0, 1))
);

-- hierarchy_depth_limit() as migrations/0273.pgsql.sql defines it. Already in `master` by
-- the time 0279 is written; restated here only because this spike does not load the real
-- migration history.
CREATE FUNCTION hierarchy_depth_limit() RETURNS INTEGER
	LANGUAGE sql IMMUTABLE PARALLEL SAFE
	AS $$ SELECT 6 $$;
