-- Real persistence, so "the write was refused" can be checked against what is stored rather
-- than against a response code. The earlier round had no store, which is exactly why it could
-- not assert that a rejected write changes nothing.
DROP TABLE IF EXISTS label_printers, label_drivers CASCADE;

CREATE TABLE label_drivers (
  driver_id TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  document JSONB NOT NULL,
  registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (driver_id, schema_version)
);

CREATE TABLE label_printers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  driver_id TEXT NOT NULL,
  driver_schema_version TEXT NOT NULL,
  model TEXT NOT NULL,
  media TEXT NOT NULL,
  settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
