<?php

namespace Victual\Middleware;

use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Server\RequestHandlerInterface as RequestHandler;
use Slim\Routing\RouteContext;

/**
 * Refuses an API request whose path carries a non-integer where the endpoint takes an
 * integer id, before the value reaches a statement.
 *
 * Every table in this schema keys on `id INTEGER GENERATED BY DEFAULT AS IDENTITY`, and
 * LessQL interpolates the value into the statement rather than binding it. So
 * `GET /api/objects/equipment/undefined` used to reach PostgreSQL as
 * `WHERE ("id" = 'undefined')`, which is a type error rather than a non-match: the
 * request answered 500 and the response body quoted the failing statement back to the
 * caller. SQLite's dynamic typing made the same request a silent non-match, which is why
 * upstream answers 404 and this fork did not. See issue #48.
 *
 * The rule this applies is the one BaseApiController::MaterialiseFiltered() already
 * states for the `query[]`/`order` surface: a value the *caller* supplied that the
 * database would reject is a 400, and the answer does not carry the driver's message.
 * This is the same rule moved one step earlier, to path parameters, where it can be
 * applied before any SQL is built at all.
 *
 * **Which parameters are integers is read from victual.openapi.json, not from a list
 * kept here.** The spec already draws the one distinction a list keyed on the parameter's
 * name cannot: `{objectId}` is an integer on `/objects/{entity}/{objectId}` and a string
 * on `/userfields/{entity}/{objectId}`, because `userfield_values.object_id` is TEXT and
 * carries a grocycode for the `stock` entity. Reading the spec is also how
 * BaseApiController resolves its entity allow-lists, for the same reason: a second list
 * is a list that drifts.
 *
 * An endpoint the spec does not describe is passed through rather than refused — a
 * missing spec entry is a documentation defect and must not become a 400 for a caller.
 * `.devtools/check-path-id-validation.php` is what stops that being a silent hole: it
 * fails the `lint` job when a route in routes.php takes a path parameter the spec does
 * not type, so "the spec did not say" cannot quietly mean "unvalidated".
 */
class PathParameterMiddleware extends BaseMiddleware
{
	/** @var array<string, string[]>|null Integer path parameters per "METHOD /path", for this request only */
	private static $IntegerParameters = null;

	public function __invoke(Request $request, RequestHandler $handler): Response
	{
		$route = RouteContext::fromRequest($request)->getRoute();

		if ($route === null)
		{
			return $handler->handle($request);
		}

		$arguments = $route->getArguments();

		foreach (self::IntegerParametersFor($request->getMethod(), $route->getPattern()) as $parameterName)
		{
			if (!array_key_exists($parameterName, $arguments))
			{
				continue;
			}

			if (filter_var($arguments[$parameterName], FILTER_VALIDATE_INT) === false)
			{
				return $this->InvalidPathParameterResponse($parameterName);
			}
		}

		return $handler->handle($request);
	}

	/**
	 * The names of the path parameters the spec types as integers for this endpoint.
	 *
	 * @return string[]
	 */
	private static function IntegerParametersFor(string $method, string $pattern): array
	{
		if (self::$IntegerParameters === null)
		{
			self::$IntegerParameters = self::ReadIntegerParametersFromSpec();
		}

		// Routes are registered inside $app->group('/api'), so the pattern carries that
		// prefix while the spec's paths do not.
		if (string_starts_with($pattern, '/api'))
		{
			$pattern = substr($pattern, strlen('/api'));
		}

		$pattern = self::StripFastRouteConstraints($pattern);

		return self::$IntegerParameters[strtoupper($method) . ' ' . $pattern] ?? [];
	}

	/**
	 * The unconstrained form of a Slim/FastRoute pattern: {kind:location|product} becomes
	 * {kind}, the same as victual.openapi.json spells it - the constraint lives in the
	 * parameter's schema there, not the path template.
	 *
	 * Reuses FastRoute's own placeholder regex (`RouteParser\Std::VARIABLE_REGEX`, PCRE
	 * recursion and all) rather than a hand-rolled one: a constraint can itself contain
	 * braces - `{id:[0-9]{1,9}}` - and a pattern that just stops at the first `}` splits
	 * that wrong, leaving a stray closing brace behind. .devtools/check-path-id-validation.php
	 * strips route patterns the same way this method does, by calling this method - a
	 * second regex here is a second regex that drifts from FastRoute's own grammar.
	 */
	public static function StripFastRouteConstraints(string $pattern): string
	{
		return preg_replace_callback(
			'~' . \FastRoute\RouteParser\Std::VARIABLE_REGEX . '~x',
			static function (array $matches): string
			{
				return '{' . $matches[1] . '}';
			},
			$pattern
		);
	}

	/**
	 * Reads victual.openapi.json once and returns the integer path parameters of every
	 * documented operation, keyed by "METHOD /path".
	 *
	 * @return array<string, string[]>
	 */
	private static function ReadIntegerParametersFromSpec(): array
	{
		$spec = json_decode(file_get_contents(__DIR__ . '/../victual.openapi.json'), true);
		$integerParameters = [];

		foreach ($spec['paths'] ?? [] as $path => $operations)
		{
			foreach ($operations as $method => $operation)
			{
				if (!is_array($operation))
				{
					continue;
				}

				foreach ($operation['parameters'] ?? [] as $parameter)
				{
					if (($parameter['in'] ?? null) === 'path' && ($parameter['schema']['type'] ?? null) === 'integer')
					{
						$integerParameters[strtoupper($method) . ' ' . $path][] = $parameter['name'];
					}
				}
			}
		}

		return $integerParameters;
	}

	/**
	 * The 400 body, in the shape BaseApiController::GenericErrorResponse() produces.
	 *
	 * Deliberately names the parameter without quoting the value back. The caller knows
	 * what it sent, the parameter name is what tells it where to look, and
	 * Victual.Api.DefaultErrorHandler puts error_message in front of the user — so a
	 * message that reflects arbitrary path input is a sink this fork spent plan 21
	 * closing.
	 */
	private function InvalidPathParameterResponse(string $parameterName): Response
	{
		$response = $this->ResponseFactory->createResponse(400)->withHeader('Content-Type', 'application/json');
		$response->getBody()->write(json_encode([
			'error_message' => 'Invalid path parameter: {' . $parameterName . '} has to be an integer'
		]));

		return $response;
	}
}
