-- SPIKE ONLY (ADR-0037). Not a migration. A reference model of the proposed objects, applied to
-- a disposable schema after the real migrations. Names and details are not final.

-- ADR-0032 tolerance for amount comparisons.
CREATE FUNCTION spike_amounts_equal(a DOUBLE PRECISION, b DOUBLE PRECISION) RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$ SELECT abs(a - b) <= GREATEST(1e-9, 1e-12 * GREATEST(abs(a), abs(b))) $$;

CREATE TABLE stock_label_retirements (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	label_uid TEXT NOT NULL REFERENCES labels (uid),      -- labels is never truncated by the importer
	retired_at TIMESTAMPTZ NOT NULL,
	snapshot JSONB NOT NULL,
	cause TEXT NOT NULL CHECK (cause IN ('consumption', 'unproven', 'legacy')),
	import_epoch BIGINT,
	booking_id BIGINT,                                    -- no foreign key: stock_log is truncated by an import
	product_id BIGINT,
	amount DOUBLE PRECISION,
	jobs_through_id BIGINT,
	revivable_until TIMESTAMPTZ,
	outcome TEXT CHECK (outcome IN ('revived', 'declined')),
	reason TEXT,
	closed_at TIMESTAMPTZ,
	revived_target_id BIGINT,
	CHECK ((cause = 'consumption') = (booking_id IS NOT NULL)),
	CHECK (cause <> 'consumption' OR (product_id IS NOT NULL AND amount IS NOT NULL AND import_epoch IS NOT NULL
		AND revivable_until IS NOT NULL AND jobs_through_id IS NOT NULL)),
	CHECK (cause = 'legacy' OR import_epoch IS NOT NULL),
	CHECK (cause = 'consumption' OR outcome = 'declined'),
	CHECK ((outcome IS NULL) = (closed_at IS NULL)),
	CHECK ((outcome = 'revived') = (revived_target_id IS NOT NULL)),
	CHECK ((outcome = 'declined') = (reason IS NOT NULL))
);
CREATE UNIQUE INDEX stock_label_retirements_booking ON stock_label_retirements (import_epoch, booking_id) WHERE booking_id IS NOT NULL;
CREATE INDEX stock_label_retirements_label ON stock_label_retirements (label_uid);

-- Writes one event for every retirement of a stock_entry label, whichever statement retired it.
CREATE FUNCTION record_stock_label_retirement() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	v_row BIGINT := (NEW.retirement_snapshot ->> 'id')::BIGINT;
	v_booking BIGINT := NULLIF(current_setting('victual.retiring_booking_id', true), '')::BIGINT;
	v_grace INTEGER := COALESCE(NULLIF(current_setting('victual.label_revival_grace_seconds', true), '')::INTEGER, 0);
	v_log RECORD;
	v_through BIGINT;
	v_proven BOOLEAN := false;
BEGIN
	IF v_booking IS NOT NULL AND v_grace > 0 THEN
		SELECT * INTO v_log FROM stock_log
		WHERE id = v_booking AND stock_row_id = v_row AND undone = 0
			AND transaction_type IN ('consume', 'inventory-correction') AND amount < 0
			AND spike_amounts_equal(-amount, (NEW.retirement_snapshot ->> 'amount')::DOUBLE PRECISION);
		v_proven := FOUND;
	END IF;
	IF v_proven THEN
		SELECT COALESCE(MAX(id), 0) INTO v_through FROM print_jobs WHERE label_uid = NEW.uid;
		INSERT INTO stock_label_retirements (label_uid, retired_at, snapshot, cause, import_epoch, booking_id, product_id, amount,
			jobs_through_id, revivable_until)
		VALUES (NEW.uid, NEW.retired_at, NEW.retirement_snapshot, 'consumption', label_current_import_epoch(), v_booking, v_log.product_id,
			-v_log.amount, v_through, NEW.retired_at + make_interval(secs => v_grace));
	ELSE
		INSERT INTO stock_label_retirements (label_uid, retired_at, snapshot, cause, import_epoch, outcome, reason, closed_at)
		VALUES (NEW.uid, NEW.retired_at, NEW.retirement_snapshot, 'unproven', label_current_import_epoch(), 'declined', 'unproven', NEW.retired_at);
	END IF;
	RETURN NULL;
END
$$;
CREATE TRIGGER stock_label_retirement_event AFTER UPDATE OF retired_at ON labels
FOR EACH ROW WHEN (OLD.retired_at IS NULL AND NEW.retired_at IS NOT NULL AND NEW.kind = 'stock_entry')
EXECUTE FUNCTION record_stock_label_retirement();

-- Retirements that predate the table: kept as history, never revivable, nothing inferred.
CREATE FUNCTION spike_backfill_legacy_retirements() RETURNS BIGINT LANGUAGE sql AS $$
	WITH ins AS (
		INSERT INTO stock_label_retirements (label_uid, retired_at, snapshot, cause, outcome, reason, closed_at)
		SELECT l.uid, l.retired_at, l.retirement_snapshot, 'legacy', 'declined', 'legacy', l.retired_at
		FROM labels l
		WHERE l.kind = 'stock_entry' AND l.retired_at IS NOT NULL
			AND NOT EXISTS (SELECT 1 FROM stock_label_retirements e WHERE e.label_uid = l.uid)
		RETURNING 1)
	SELECT count(*) FROM ins
$$;

-- The revival step of an undo. Called inside the undo transaction, after the stock row was
-- rebuilt. p_now exists only so the spike can test the expiry boundary exactly.
CREATE FUNCTION spike_revive_stock_entry_label(p_booking_id BIGINT, p_restored_row BIGINT, p_now TIMESTAMPTZ DEFAULT NULL)
RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
	e stock_label_retirements%ROWTYPE;
	b stock_log%ROWTYPE;
	r stock%ROWTYPE;
	v_label labels%ROWTYPE;
	v_epoch BIGINT;
	v_now TIMESTAMPTZ;
BEGIN
	PERFORM pg_advisory_xact_lock(109038);                 -- the import lock (LabelIdentityService::IMPORT_LOCK)
	v_epoch := label_current_import_epoch();
	SELECT * INTO e FROM stock_label_retirements
	WHERE import_epoch = v_epoch AND booking_id = p_booking_id AND outcome IS NULL;
	IF NOT FOUND THEN RETURN 'no_reference'; END IF;

	SELECT * INTO v_label FROM labels WHERE uid = e.label_uid FOR UPDATE;           -- labels first ...
	SELECT * INTO e FROM stock_label_retirements WHERE id = e.id FOR UPDATE;        -- ... then the event
	IF e.outcome IS NOT NULL THEN RETURN 'no_reference'; END IF;

	v_now := COALESCE(p_now, clock_timestamp());
	IF v_now >= e.revivable_until THEN
		UPDATE stock_label_retirements SET outcome = 'declined', reason = 'expired', closed_at = v_now WHERE id = e.id;
		RETURN 'declined:expired';
	END IF;
	IF v_label.retired_at IS NULL THEN
		UPDATE stock_label_retirements SET outcome = 'declined', reason = 'label_not_retired', closed_at = v_now WHERE id = e.id;
		RETURN 'declined:label_not_retired';
	END IF;

	SELECT * INTO b FROM stock_log WHERE id = p_booking_id;
	SELECT * INTO r FROM stock WHERE id = p_restored_row;
	IF NOT FOUND OR b.product_id <> e.product_id OR b.stock_row_id IS DISTINCT FROM (e.snapshot ->> 'id')::BIGINT
		OR NOT spike_amounts_equal(-b.amount, e.amount) OR r.product_id <> e.product_id
		OR NOT spike_amounts_equal(r.amount, e.amount) OR r.import_epoch <> v_epoch THEN
		UPDATE stock_label_retirements SET outcome = 'declined', reason = 'mismatch', closed_at = v_now WHERE id = e.id;
		RETURN 'declined:mismatch';
	END IF;
	IF EXISTS (SELECT 1 FROM labels WHERE kind = 'stock_entry' AND target_id = p_restored_row AND retired_at IS NULL) THEN
		UPDATE stock_label_retirements SET outcome = 'declined', reason = 'target_labelled', closed_at = v_now WHERE id = e.id;
		RETURN 'declined:target_labelled';
	END IF;

	UPDATE labels SET retired_at = NULL, target_id = p_restored_row, retirement_snapshot = NULL WHERE uid = e.label_uid;
	UPDATE stock_label_retirements SET outcome = 'revived', closed_at = v_now, revived_target_id = p_restored_row WHERE id = e.id;
	RETURN 'revived';
END
$$;

-- Emulates the application's hook: ConsumeProduct() will set these two transaction-local
-- settings after it writes a whole-row booking and before it deletes the row. The spike does
-- not modify StockService, so a trigger on stock_log sets them at the same point.
CREATE FUNCTION spike_emulate_retirement_context() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
	PERFORM set_config('victual.retiring_booking_id', NEW.id::TEXT, true);
	PERFORM set_config('victual.label_revival_grace_seconds', '2592000', true);
	RETURN NULL;
END
$$;
CREATE TRIGGER spike_retirement_context AFTER INSERT ON stock_log
FOR EACH ROW WHEN (NEW.stock_row_id IS NOT NULL AND NEW.amount < 0 AND NEW.transaction_type IN ('consume', 'inventory-correction'))
EXECUTE FUNCTION spike_emulate_retirement_context();
