-- ADR-0019 gates 2 and 3 — the minimum schema the behaviour needs.
-- Disposable: this is not migration 0270, it is the smallest thing that can be wrong.

DROP TABLE IF EXISTS print_evidence, print_attempts, print_jobs, outbox,
                     worker_credentials, pending_rotations, pairing_material,
                     label_workers CASCADE;

CREATE TABLE outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  delivered_at TIMESTAMPTZ,
  dead_lettered_at TIMESTAMPTZ,
  attempts INT NOT NULL DEFAULT 0,
  last_error TEXT
);

CREATE TABLE label_workers (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT true
);

-- Decision item 5: the consumer's own per-job state, which cannot live on the shared outbox.
CREATE TABLE print_jobs (
  outbox_id BIGINT PRIMARY KEY REFERENCES outbox(id),
  printer_id INT NOT NULL,
  worker_id INT NOT NULL REFERENCES label_workers(id),
  attempts_authorized INT NOT NULL DEFAULT 1,
  current_attempt_id BIGINT,
  outcome TEXT,
  artifact_ready BOOLEAN NOT NULL DEFAULT true
);

-- Decision item 5: one row per claim, fenced by the unique constraint rather than by the lock.
CREATE TABLE print_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outbox_id BIGINT NOT NULL REFERENCES outbox(id),
  attempt_number INT NOT NULL,
  worker_id INT NOT NULL REFERENCES label_workers(id),
  claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  lease_expires_at TIMESTAMPTZ NOT NULL,
  absolute_deadline TIMESTAMPTZ NOT NULL,
  bytes_sent_at TIMESTAMPTZ,
  device_reported_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  outcome TEXT,
  error TEXT,
  superseded BOOLEAN NOT NULL DEFAULT false,
  UNIQUE (outbox_id, attempt_number)
);

CREATE TABLE print_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id BIGINT NOT NULL REFERENCES print_attempts(id),
  source TEXT NOT NULL,
  submission_id TEXT NOT NULL,
  observed JSONB NOT NULL,
  UNIQUE (source, submission_id)
);

-- Credentials: stored as a SHA-256 hash with a hint, exactly as migration 0264 leaves api_keys.
CREATE TABLE worker_credentials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id INT NOT NULL REFERENCES label_workers(id),
  key_hash TEXT NOT NULL UNIQUE,
  key_hint TEXT NOT NULL,
  session_id TEXT NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  session_expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ
);

-- The replay record. It holds no plaintext: see 03-rotation.sql for why that is possible.
CREATE TABLE pending_rotations (
  rotation_request_id TEXT PRIMARY KEY,
  from_credential_id BIGINT NOT NULL REFERENCES worker_credentials(id),
  to_credential_id BIGINT REFERENCES worker_credentials(id),
  worker_material TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE pairing_material (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id INT NOT NULL REFERENCES label_workers(id),
  secret_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ
);
